# Peer-graded Assignment: Capstone Project - The Battle of Neighborhoods

This report includes six sections as follows:

* Introduction 
* Data 
* Methodology 
* Results 
* Discussion 
* Conclusion

## Introduction


Manchester and Liverpool are two major cities in North West England. Both cities are noted for their culture, architecture, musical exports, sports clubs and transport links. 

According to Wikepedia (www.wikipedia.org):
    
    * Manchester is the third-most visited city in the UK with a population of 545,500 as of 2017 and with a GDP of $102.3bn (2015). The economy grew relatively strongly between 2002 and 2012. 
    According to 2019 property investment research, Manchester is rated as the second location for "The Best Places to Invest in Property In The UK". 
    
    * Liverpool is the fifth-largest city in the UK with a population of 2.24 million in 2011 and with a GDP at $65.8bn (2014). The Economy of Liverpool is one of the largest within the UK.
    The important component of Liverpool's economy are the tuourism and leisure sectors. Car manufacturing also takes place in the city. 
    
In this project, the above two cities will be compared in details using machine learning segmentation and clustering along with Foursquare data. 
The objectives include: 

    * How similar these two cities are? 
    * Which city is better for living for a university student?

## Data

In order to apply this study, basic geo data of this two cities need to be collected:
    
    * Postcode for Liverpool (https://en.wikipedia.org/wiki/L_postcode_area)
    * Postcode for Manchester (https://en.wikipedia.org/wiki/M_postcode_area)
            
    The latitude and longitude data also required:
    
    * (https://www.freemaptools.com/download/outcode-postcodes/postcode-outcodes.csv)

In [2]:
#pip install wikipedia, lxml
!conda install -c conda-forge wikipedia --yes 
!conda install -c conda-forge lxml --yes
import pandas as pd 
 
import wikipedia as wp
from bs4 import BeautifulSoup

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.11
  latest version: 4.7.11

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/jupyterlab/conda/envs/python

  added / updated specs:
    - wikipedia


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    soupsieve-1.9.2            |           py36_0          59 KB  conda-forge
    wikipedia-1.4.0            |             py_2          13 KB  conda-forge
    beautifulsoup4-4.8.0       |           py36_0         144 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         216 KB

The following NEW packages will be INSTALLED:

    soupsieve:      1.9.2-py36_0 conda-forge
    wikipedia:      1.4.0-py_2   conda-forge

The following packages will be UPDATED:

    beautifulsoup4: 4.6.3-py37_0             --> 4.8.0-py36_0 conda-forge


Downloading and Extracting Packages
soupsieve-1.9.2      | 59 KB     | ##################################### | 100%
wikipedia-1.4.0      | 13 KB     | ##################################### | 100%
beautifulsoup4-4.8.0 | 144 KB    | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.11
  latest version: 4.7.11

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/jupyterlab/conda/envs/python

  added / updated specs:
    - lxml


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    lxml-4.4.1                 |   py36h7ec2d77_0         1.6 MB  conda-forge

The following packages will be UPDATED:

    lxml: 4.2.5-py37hefd8a0e_0 --> 4.4.1-py36h7ec2d77_0 conda-forge


Downloading and Extracting Packages
lxml-4.4.1           | 1.6 MB    | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

In [3]:
# get postcode data for Manchester and Liverpool
html_m = wp.page("M postcode area").html().encode("UTF-8")
html_l = wp.page("L postcode area").html().encode("UTF-8")
df_m = pd.read_html(html_m, header = 0)[1]
df_l = pd.read_html(html_l, header = 0)[1]
df_m = df_m.rename(columns={'Postcode district': 'postcode'}) 
df_l = df_l.rename(columns={'Postcode district': 'postcode'})

In [4]:
df_m.shape

(52, 4)

In [5]:
df_m

,postcode,Post town,Coverage,Local authority area
0,M1,MANCHESTER,"Piccadilly, City Centre, Market Street",Manchester
1,M2,MANCHESTER,"Deansgate, City Centre",Manchester
2,"M3(Sectors 1, 2, 3, 4 and 9)",MANCHESTER,"City Centre, Deansgate, Castlefield",Manchester
3,"M3(Sectors 5, 6 and 7)",SALFORD,"Blackfriars, Greengate, Trinity",Salford
4,M4,MANCHESTER,"Ancoats, Northern Quarter, Strangeways",Manchester
5,M5,SALFORD,"Ordsall, Seedley, Weaste, University",Salford
6,M6,SALFORD,"Pendleton, Irlams o' th' Height, Langworthy, S...",Salford
7,M7,SALFORD,"Higher Broughton, Cheetwood, Lower Broughton, ...",Salford
8,M8,MANCHESTER,"Crumpsall, Cheetham Hill",Manchester
9,M9,MANCHESTER,"Harpurhey, Blackley",Manchester
10,M11,MANCHESTER,"Clayton, Openshaw, Beswick",Manchester
11,M12,MANCHESTER,"Ardwick, Longsight, Chorlton-on-Medlock",Manchester
12,M13,MANCHESTER,"Ardwick, Longsight, Chorlton-on-Medlock",Manchester
13,M14,MANCHESTER,"Fallowfield, Moss Side, Ladybarn, Rusholme, Lo...",Manchester
14,M15,MANCHESTER,"Hulme, Manchester Science Park, Old Trafford","Manchester, Trafford"
15,M16,MANCHESTER,"Firswood, Old Trafford, Whalley Range, Moss Side","Manchester, Trafford"
16,M17,MANCHESTER,"Trafford Park, The Trafford Centre",Trafford
17,M18,MANCHESTER,"Abbey Hey, Gorton",Manchester
18,M19,MANCHESTER,"Levenshulme, Burnage","Manchester, Stockport"
19,M20,MANCHESTER,"Didsbury, Withington",Manchester
20,M21,MANCHESTER,"Chorlton-cum-Hardy, Barlow Moor",Manchester
21,M22,MANCHESTER,"Wythenshawe, Northenden, Sharston Industrial Area",Manchester
22,M23,MANCHESTER,"Baguley, Brooklands (Manchester and Trafford),...","Manchester, Trafford"
23,M24,MANCHESTER,"Middleton, Alkrington, Chadderton","Rochdale, Oldham"
24,M25,MANCHESTER,"Prestwich, Sedgley Park, Simister",Bury
25,M26,MANCHESTER,"Radcliffe, Stoneclough","Bury, Bolton"
26,M27,MANCHESTER,"Swinton, Clifton, Pendlebury, Wardley, Agecroft",Salford
27,M28,MANCHESTER,"Worsley, Walkden, Boothstown, Mosley Common, W...","Salford, Wigan"
28,M29,MANCHESTER,"Tyldesley, Astley",Wigan
29,M30,MANCHESTER,"Eccles, Monton, Peel Green, Winton, Patricroft...",Salford
30,M31,MANCHESTER,"Carrington, Partington",Trafford
31,M32,MANCHESTER,"Stretford, Trafford Park",Trafford
32,M33,SALE,"Sale, Brooklands (Manchester and Trafford)","Trafford, Manchester"
33,M34,MANCHESTER,"Denton, Audenshaw",Tameside
34,M35,MANCHESTER,Failsworth,Oldham
35,M38,MANCHESTER,Little Hulton,Salford
36,M40,MANCHESTER,"Collyhurst, Miles Platting, Moston, New Moston...",Manchester
37,M41,MANCHESTER,"Urmston, Davyhulme, Flixton, Trafford Park",Trafford
38,M43,MANCHESTER,Droylsden,Tameside
39,M44,MANCHESTER,"Irlam, Cadishead",Salford
40,M45,MANCHESTER,Whitefield,Bury
41,M46,MANCHESTER,Atherton,Wigan
42,M50,SALFORD,"Salford Quays, MediaCityUK",Salford
43,M60(Sectors 1 and 7),MANCHESTER,Large user and PO Box (located geographically ...,Manchester
44,M60(Sectors 2 and 8),MANCHESTER,Large user and PO Box (located geographically ...,Manchester
45,M60(Sectors 3 and 9),MANCHESTER,Large user and PO Box (located geographically ...,Manchester
46,M60(Sectors 4 and 0),MANCHESTER,Large user and PO Box (located geographically ...,Manchester
47,M60(Sectors 5 and 6),MANCHESTER,Manchester X,Manchester
48,M60(Sector 9),SALFORD,Large user and PO Box,Salford
49,M61,MANCHESTER,Manchester X,Manchester
50,M90,MANCHESTER,Manchester Airport,Manchester
51,M99,MANCHESTER,Manchester X; JD Williams (located geographica...,Manchester

In [6]:
df_l

,postcode,Post town,Coverage,Local authority area
0,L1,LIVERPOOL,City Centre,Liverpool
1,L2,LIVERPOOL,City Centre,Liverpool
2,L3,LIVERPOOL,"City Centre, Everton, Vauxhall",Liverpool
3,L4,LIVERPOOL,"Anfield, Kirkdale, Walton",Liverpool
4,L5,LIVERPOOL,"Anfield, Everton, Kirkdale, Vauxhall",Liverpool
5,L6,LIVERPOOL,"Anfield, City Centre, Everton, Fairfield, Kens...",Liverpool
6,L7,LIVERPOOL,"City Centre, Edge Hill, Fairfield, Kensington",Liverpool
7,L8,LIVERPOOL,"City Centre, Dingle, Toxteth",Liverpool
8,L9,LIVERPOOL,"Aintree, Fazakerley, Orrell Park, Walton","Liverpool, Sefton"
9,L10,LIVERPOOL,"Aintree Village, Fazakerley","Sefton, Liverpool, Knowsley"
10,L11,LIVERPOOL,"Clubmoor, Croxteth, Gillmoss, Norris Green",Liverpool
11,L12,LIVERPOOL,"Croxteth Park, West Derby",Liverpool
12,L13,LIVERPOOL,"Clubmoor, Old Swan, Stoneycroft, Tuebrook",Liverpool
13,L14,LIVERPOOL,"Broadgreen, Dovecot, Knotty Ash, Page Moss","Liverpool, Knowsley"
14,L15,LIVERPOOL,Wavertree,Liverpool
15,L16,LIVERPOOL,"Broadgreen, Bowring Park, Childwall","Liverpool, Knowsley"
16,L17,LIVERPOOL,"Aigburth, St Michael's Hamlet, Sefton Park",Liverpool
17,L18,LIVERPOOL,"Allerton, Mossley Hill",Liverpool
18,L19,LIVERPOOL,"Garston, Grassendale, Aigburth,",Liverpool
19,L20,BOOTLE,"Bootle, Orrell","Sefton, Liverpool"
20,L20,LIVERPOOL,Kirkdale,Liverpool
21,L21,LIVERPOOL,"Ford, Litherland, Seaforth","Sefton, Liverpool"
22,L22,LIVERPOOL,Waterloo,Sefton
23,L23,LIVERPOOL,"Blundellsands, Brighton-le-Sands, Crosby, Litt...",Sefton
24,L24,LIVERPOOL,"Hale, Speke","Halton, Liverpool"
25,L25,LIVERPOOL,"Belle Vale, Gateacre, Hunts Cross, Woolton, Ha...","Liverpool, Knowsley"
26,L26,LIVERPOOL,Halewood,"Liverpool, Knowsley"
27,L27,LIVERPOOL,Netherley,Liverpool
28,L28,LIVERPOOL,Stockbridge Village,"Liverpool, Knowsley"
29,L29,LIVERPOOL,"Lunt, Sefton Village",Sefton
30,L30,BOOTLE,"Bootle, Netherton",Sefton
31,L31,LIVERPOOL,"Maghull, Lydiate, Melling, Waddicar",Sefton
32,L32,LIVERPOOL,Kirkby,Knowsley
33,L33,LIVERPOOL,Kirkby,Knowsley
34,L34,PRESCOT,"Prescot, Knowsley Village",Knowsley
35,L35,PRESCOT,"Prescot, Whiston, Rainhill","Knowsley, St Helens"
36,L36,LIVERPOOL,"Huyton, Roby, Tarbock",Knowsley
37,L37,LIVERPOOL,"Formby, Little Altcar, Great Altcar","Sefton, West Lancashire"
38,L38,LIVERPOOL,"Ince Blundell, Hightown","Sefton, West Lancashire"
39,L39,ORMSKIRK,"Ormskirk, Aughton",West Lancashire
40,L40,ORMSKIRK,"Burscough, Mawdesley, Scarisbrick, Rufford, Ho...","West Lancashire, Chorley"
41,L67,LIVERPOOL,Littlewoods Pools[4],non-geographic
42,L68,LIVERPOOL,Vernons Pools[4],non-geographic
43,L69,LIVERPOOL,"PO boxes in central Liverpool, government depa...",non-geographic
44,L70,LIVERPOOL,seasonal response mail[4],non-geographic
45,L71,LIVERPOOL,American Express[4],non-geographic
46,L72,LIVERPOOL,Littlewoods[4],non-geographic
47,L73,LIVERPOOL,"BT Group, large Selectapost users[4]",non-geographic
48,L74,LIVERPOOL,HM Revenue and Customs (Customs and Excise)[4],non-geographic
49,L75,LIVERPOOL,HM Revenue and Customs (Inland Revenue)[4],non-geographic
50,L80,BOOTLE,NaN,non-geographic[5]

In [7]:
# get the Latitude and Longitude of each postcode

postcode = pd.read_csv("https://www.freemaptools.com/download/outcode-postcodes/postcode-outcodes.csv")

In [8]:
postcode.head

<bound method NDFrame.head of         id postcode  latitude  longitude
0        2     AB10  57.13514   -2.11731
1        3     AB11  57.13875   -2.09089
2        4     AB12  57.10100   -2.11060
3        5     AB13  57.10801   -2.23776
4        6     AB14  57.10076   -2.27073
...    ...      ...       ...        ...
2998  3001     WV98   0.00000    0.00000
2999  3002      S95   0.00000    0.00000
3000  3003     PA80   0.00000    0.00000
3001  3004      L80   0.00000    0.00000
3002  3005      BS0   0.00000    0.00000

[3003 rows x 4 columns]>

In [9]:
# tidy the table, delete the first column
postcode = postcode.drop('id',1)
postcode.head
# df.drop('column_name', axis=1, inplace=True)

<bound method NDFrame.head of      postcode  latitude  longitude
0        AB10  57.13514   -2.11731
1        AB11  57.13875   -2.09089
2        AB12  57.10100   -2.11060
3        AB13  57.10801   -2.23776
4        AB14  57.10076   -2.27073
...       ...       ...        ...
2998     WV98   0.00000    0.00000
2999      S95   0.00000    0.00000
3000     PA80   0.00000    0.00000
3001      L80   0.00000    0.00000
3002      BS0   0.00000    0.00000

[3003 rows x 3 columns]>

In [10]:
postcode.shape

(3003, 3)

In [11]:
# Merge the geocodes into the data frames of the two cities

import requests
import io


df_m = pd.merge(postcode, df_m, on='postcode')
df_m.shape
df_m

,postcode,latitude,longitude,Post town,Coverage,Local authority area
0,M1,53.477340,-2.235080,MANCHESTER,"Piccadilly, City Centre, Market Street",Manchester
1,M11,53.478340,-2.179330,MANCHESTER,"Clayton, Openshaw, Beswick",Manchester
2,M12,53.464820,-2.201870,MANCHESTER,"Ardwick, Longsight, Chorlton-on-Medlock",Manchester
3,M13,53.460300,-2.213890,MANCHESTER,"Ardwick, Longsight, Chorlton-on-Medlock",Manchester
4,M14,53.447700,-2.224370,MANCHESTER,"Fallowfield, Moss Side, Ladybarn, Rusholme, Lo...",Manchester
5,M15,53.465630,-2.250080,MANCHESTER,"Hulme, Manchester Science Park, Old Trafford","Manchester, Trafford"
6,M16,53.454810,-2.263570,MANCHESTER,"Firswood, Old Trafford, Whalley Range, Moss Side","Manchester, Trafford"
7,M17,53.469060,-2.317890,MANCHESTER,"Trafford Park, The Trafford Centre",Trafford
8,M18,53.461270,-2.168710,MANCHESTER,"Abbey Hey, Gorton",Manchester
9,M19,53.436960,-2.194210,MANCHESTER,"Levenshulme, Burnage","Manchester, Stockport"
10,M2,53.480030,-2.242630,MANCHESTER,"Deansgate, City Centre",Manchester
11,M20,53.425210,-2.230270,MANCHESTER,"Didsbury, Withington",Manchester
12,M21,53.437710,-2.270990,MANCHESTER,"Chorlton-cum-Hardy, Barlow Moor",Manchester
13,M22,53.385600,-2.258630,MANCHESTER,"Wythenshawe, Northenden, Sharston Industrial Area",Manchester
14,M23,53.399020,-2.287290,MANCHESTER,"Baguley, Brooklands (Manchester and Trafford),...","Manchester, Trafford"
15,M24,53.551130,-2.196240,MANCHESTER,"Middleton, Alkrington, Chadderton","Rochdale, Oldham"
16,M25,53.528500,-2.274590,MANCHESTER,"Prestwich, Sedgley Park, Simister",Bury
17,M26,53.561610,-2.333690,MANCHESTER,"Radcliffe, Stoneclough","Bury, Bolton"
18,M27,53.512160,-2.336310,MANCHESTER,"Swinton, Clifton, Pendlebury, Wardley, Agecroft",Salford
19,M28,53.514670,-2.396660,MANCHESTER,"Worsley, Walkden, Boothstown, Mosley Common, W...","Salford, Wigan"
20,M29,53.508160,-2.456920,MANCHESTER,"Tyldesley, Astley",Wigan
21,M30,53.484240,-2.354180,MANCHESTER,"Eccles, Monton, Peel Green, Winton, Patricroft...",Salford
22,M31,53.419300,-2.421360,MANCHESTER,"Carrington, Partington",Trafford
23,M32,53.450210,-2.308720,MANCHESTER,"Stretford, Trafford Park",Trafford
24,M33,53.420500,-2.325060,SALE,"Sale, Brooklands (Manchester and Trafford)","Trafford, Manchester"
25,M34,53.455940,-2.117480,MANCHESTER,"Denton, Audenshaw",Tameside
26,M35,53.507140,-2.152300,MANCHESTER,Failsworth,Oldham
27,M38,53.531670,-2.420960,MANCHESTER,Little Hulton,Salford
28,M4,53.484550,-2.229090,MANCHESTER,"Ancoats, Northern Quarter, Strangeways",Manchester
29,M40,53.503490,-2.189990,MANCHESTER,"Collyhurst, Miles Platting, Moston, New Moston...",Manchester
30,M41,53.450950,-2.362940,MANCHESTER,"Urmston, Davyhulme, Flixton, Trafford Park",Trafford
31,M43,53.483780,-2.147700,MANCHESTER,Droylsden,Tameside
32,M44,53.440860,-2.426090,MANCHESTER,"Irlam, Cadishead",Salford
33,M45,53.547340,-2.288290,MANCHESTER,Whitefield,Bury
34,M46,53.526010,-2.490310,MANCHESTER,Atherton,Wigan
35,M5,53.479030,-2.284820,SALFORD,"Ordsall, Seedley, Weaste, University",Salford
36,M6,53.491590,-2.296960,SALFORD,"Pendleton, Irlams o' th' Height, Langworthy, S...",Salford
37,M7,53.505160,-2.260860,SALFORD,"Higher Broughton, Cheetwood, Lower Broughton, ...",Salford
38,M8,53.508800,-2.238270,MANCHESTER,"Crumpsall, Cheetham Hill",Manchester
39,M9,53.521430,-2.212690,MANCHESTER,"Harpurhey, Blackley",Manchester
40,M90,53.363090,-2.276530,MANCHESTER,Manchester Airport,Manchester
41,M50,53.479393,-2.304275,SALFORD,"Salford Quays, MediaCityUK",Salford
42,M99,53.484512,-2.234866,MANCHESTER,Manchester X; JD Williams (located geographica...,Manchester
43,M61,0.000000,0.000000,MANCHESTER,Manchester X,Manchester

In [12]:
df_l = pd.merge(postcode, df_l, on='postcode')

In [13]:
df_l.shape

(51, 6)

In [14]:
df_l

,postcode,latitude,longitude,Post town,Coverage,Local authority area
0,L1,53.402540,-2.979280,LIVERPOOL,City Centre,Liverpool
1,L10,53.473980,-2.926680,LIVERPOOL,"Aintree Village, Fazakerley","Sefton, Liverpool, Knowsley"
2,L11,53.448010,-2.914070,LIVERPOOL,"Clubmoor, Croxteth, Gillmoss, Norris Green",Liverpool
3,L12,53.434670,-2.894210,LIVERPOOL,"Croxteth Park, West Derby",Liverpool
4,L13,53.417400,-2.919430,LIVERPOOL,"Clubmoor, Old Swan, Stoneycroft, Tuebrook",Liverpool
5,L14,53.418610,-2.878830,LIVERPOOL,"Broadgreen, Dovecot, Knotty Ash, Page Moss","Liverpool, Knowsley"
6,L15,53.397630,-2.919010,LIVERPOOL,Wavertree,Liverpool
7,L16,53.398760,-2.887440,LIVERPOOL,"Broadgreen, Bowring Park, Childwall","Liverpool, Knowsley"
8,L17,53.377690,-2.939620,LIVERPOOL,"Aigburth, St Michael's Hamlet, Sefton Park",Liverpool
9,L18,53.380640,-2.906610,LIVERPOOL,"Allerton, Mossley Hill",Liverpool
10,L19,53.359100,-2.901650,LIVERPOOL,"Garston, Grassendale, Aigburth,",Liverpool
11,L2,53.406960,-2.988410,LIVERPOOL,City Centre,Liverpool
12,L20,53.452810,-2.987970,BOOTLE,"Bootle, Orrell","Sefton, Liverpool"
13,L20,53.452810,-2.987970,LIVERPOOL,Kirkdale,Liverpool
14,L21,53.470700,-2.998930,LIVERPOOL,"Ford, Litherland, Seaforth","Sefton, Liverpool"
15,L22,53.476760,-3.026200,LIVERPOOL,Waterloo,Sefton
16,L23,53.491180,-3.022030,LIVERPOOL,"Blundellsands, Brighton-le-Sands, Crosby, Litt...",Sefton
17,L24,53.343390,-2.836720,LIVERPOOL,"Hale, Speke","Halton, Liverpool"
18,L25,53.378270,-2.862960,LIVERPOOL,"Belle Vale, Gateacre, Hunts Cross, Woolton, Ha...","Liverpool, Knowsley"
19,L26,53.364100,-2.832620,LIVERPOOL,Halewood,"Liverpool, Knowsley"
20,L27,53.387440,-2.837580,LIVERPOOL,Netherley,Liverpool
21,L28,53.434900,-2.864110,LIVERPOOL,Stockbridge Village,"Liverpool, Knowsley"
22,L29,53.506790,-2.983190,LIVERPOOL,"Lunt, Sefton Village",Sefton
23,L3,53.408800,-2.983940,LIVERPOOL,"City Centre, Everton, Vauxhall",Liverpool
24,L30,53.484420,-2.970620,BOOTLE,"Bootle, Netherton",Sefton
25,L31,53.513460,-2.936590,LIVERPOOL,"Maghull, Lydiate, Melling, Waddicar",Sefton
26,L32,53.477860,-2.889090,LIVERPOOL,Kirkby,Knowsley
27,L33,53.489650,-2.875770,LIVERPOOL,Kirkby,Knowsley
28,L34,53.436140,-2.814450,PRESCOT,"Prescot, Knowsley Village",Knowsley
29,L35,53.414780,-2.782440,PRESCOT,"Prescot, Whiston, Rainhill","Knowsley, St Helens"
30,L36,53.414390,-2.839620,LIVERPOOL,"Huyton, Roby, Tarbock",Knowsley
31,L37,53.557350,-3.062880,LIVERPOOL,"Formby, Little Altcar, Great Altcar","Sefton, West Lancashire"
32,L38,53.524200,-3.049980,LIVERPOOL,"Ince Blundell, Hightown","Sefton, West Lancashire"
33,L39,53.561420,-2.895370,ORMSKIRK,"Ormskirk, Aughton",West Lancashire
34,L4,53.437750,-2.960520,LIVERPOOL,"Anfield, Kirkdale, Walton",Liverpool
35,L40,53.602270,-2.840320,ORMSKIRK,"Burscough, Mawdesley, Scarisbrick, Rufford, Ho...","West Lancashire, Chorley"
36,L5,53.425050,-2.975290,LIVERPOOL,"Anfield, Everton, Kirkdale, Vauxhall",Liverpool
37,L6,53.418960,-2.949560,LIVERPOOL,"Anfield, City Centre, Everton, Fairfield, Kens...",Liverpool
38,L69,53.407090,-2.973370,LIVERPOOL,"PO boxes in central Liverpool, government depa...",non-geographic
39,L7,53.405490,-2.947760,LIVERPOOL,"City Centre, Edge Hill, Fairfield, Kensington",Liverpool
40,L70,53.408910,-2.970400,LIVERPOOL,seasonal response mail[4],non-geographic
41,L8,53.390090,-2.962460,LIVERPOOL,"City Centre, Dingle, Toxteth",Liverpool
42,L9,53.461200,-2.952010,LIVERPOOL,"Aintree, Fazakerley, Orrell Park, Walton","Liverpool, Sefton"
43,L67,53.428970,-2.958583,LIVERPOOL,Littlewoods Pools[4],non-geographic
44,L68,53.473055,-2.960690,LIVERPOOL,Vernons Pools[4],non-geographic
45,L71,53.439492,-2.971429,LIVERPOOL,American Express[4],non-geographic
46,L72,53.480300,-2.988368,LIVERPOOL,Littlewoods[4],non-geographic
47,L73,53.406399,-2.975554,LIVERPOOL,"BT Group, large Selectapost users[4]",non-geographic
48,L74,53.393801,-2.988061,LIVERPOOL,HM Revenue and Customs (Customs and Excise)[4],non-geographic
49,L75,53.438613,-2.985222,LIVERPOOL,HM Revenue and Customs (Inland Revenue)[4],non-geographic
50,L80,0.000000,0.000000,BOOTLE,NaN,non-geographic[5]

# Methodology

In this section, the Foursquare API will be applied to expolore neighborhoods in both cities, Manchester and Liverpool. Then, the most common venue categories in each neighborhood will be explored.
K-means clustering algorithm will be used to group the neighborhoods into clusters. 
Clustered data will be presented by using the Folium library.

### Import necessary Libraries

In [15]:
import requests # library to handle requests
import pandas as pd # library for data analsysis
import numpy as np # library to handle data in a vectorized manner
import random # library for random number generation

!conda install -c conda-forge geopy --yes 
from geopy.geocoders import Nominatim # module to convert an address into latitude and longitude values

# libraries for displaying images
from IPython.display import Image 
from IPython.core.display import HTML 
    
# tranforming json file into a pandas dataframe library
from pandas.io.json import json_normalize

!conda install -c conda-forge folium=0.5.0 --yes
import folium # plotting library

print('Folium installed')
print('Libraries imported.')

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.11
  latest version: 4.7.11

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/jupyterlab/conda/envs/python

  added / updated specs:
    - geopy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    geopy-1.20.0               |             py_0          57 KB  conda-forge
    geographiclib-1.49         |             py_0          32 KB  conda-forge
    ------------------------------------------------------------
                                           Total:          90 KB

The following NEW packages will be INSTALLED:

    geographiclib: 1.49-py_0   conda-forge
    geopy:         1.20.0-py_0 conda-forge


Downloading and Extracting Packages
geopy-1.20.0         | 57 KB     | ##################################### | 100%
geographiclib-1.49   | 32 KB     | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.11
  latest version: 4.7.11

Please update conda by running

    $ conda update -n base -c defaults conda



# All requested packages already installed.

Folium installed
Libraries imported.

### Define Foursquare Credentials and Version

In [16]:
CLIENT_ID = '40TA5YCVA3CXTBIWMNPDMBKLDL4O4BVC5E4BFN5KXKMMKHL4' #  Foursquare ID
CLIENT_SECRET = 'OFICYUUXDQKDMPHZOTTNFIWVMK5EFL23DO1HPXN2SKZMBJZM' #  Foursquare Secret
VERSION = '20180604'
LIMIT = 30
print('My credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

My credentails:
CLIENT_ID: 40TA5YCVA3CXTBIWMNPDMBKLDL4O4BVC5E4BFN5KXKMMKHL4
CLIENT_SECRET:OFICYUUXDQKDMPHZOTTNFIWVMK5EFL23DO1HPXN2SKZMBJZM

### Search for a specific venue category

For example, let's say we love Chinese food. Let's have a look of number of Chinese restaurant around The University of Liverpool and The University of Manchester :)

##### Chinese restaurants around The University of Liverpool

In [17]:
address_l = 'Chatham St, Liverpool L69 7ZN'

geolocator_l = Nominatim(user_agent="foursquare_agent")
location_l = geolocator_l.geocode(address_l)
latitude_l = location_l.latitude
longitude_l = location_l.longitude
print(latitude_l, longitude_l)

53.4001881 -2.9644371

In [18]:
search_query= 'Chinese'
radius_l = 1000
print(search_query + ' .... OK!')
url_l = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'.format(CLIENT_ID, CLIENT_SECRET, latitude_l, longitude_l, VERSION, search_query, radius_l, LIMIT)
url_l
results_l = requests.get(url_l).json()
results_l

Chinese .... OK!

{'meta': {'code': 200, 'requestId': '5d52af455bc9e30024d2d7c9'},
 'response': {'venues': [{'id': '544e9938498e020c02a65b06',
    'name': 'Campus real Chinese restaurant',
    'location': {'address': '12 Myrtle Street',
     'crossStreet': 'Liverpool',
     'lat': 53.40097,
     'lng': -2.966229,
     'labeledLatLngs': [{'label': 'display',
       'lat': 53.40097,
       'lng': -2.966229}],
     'distance': 147,
     'postalCode': 'L7 7DP',
     'cc': 'GB',
     'country': 'United Kingdom',
     'formattedAddress': ['12 Myrtle Street (Liverpool)',
      'L7 7DP',
      'United Kingdom']},
    'categories': [{'id': '4bf58dd8d48988d145941735',
      'name': 'Chinese Restaurant',
      'pluralName': 'Chinese Restaurants',
      'shortName': 'Chinese',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/asian_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1565699909',
    'hasPerk': False},
   {'id': '54198a46498efed5afdc5d80',
    'name': 'Lida Chinese supermarket',
    'location': {'lat': 53.4008062956977,
     'lng': -2.9615591907227645,
     'labeledLatLngs': [{'label': 'display',
       'lat': 53.4008062956977,
       'lng': -2.9615591907227645}],
     'distance': 203,
     'cc': 'GB',
     'country': 'United Kingdom',
     'formattedAddress': ['United Kingdom']},
    'categories': [{'id': '4d954b0ea243a5684a65b473',
      'name': 'Convenience Store',
      'pluralName': 'Convenience Stores',
      'shortName': 'Convenience Store',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/shops/conveniencestore_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1565699909',
    'hasPerk': False},
   {'id': '4d9092e3d4ec8cfa1fb0a589',
    'name': 'Arch Chinese Restaurant And Takeaway',
    'location': {'address': '9-13 Berry St.',
     'lat': 53.400157,
     'lng': -2.976411,
     'labeledLatLngs': [{'label': 'display',
       'lat': 53.400157,
       'lng': -2.976411}],
     'distance': 794,
     'postalCode': 'L1 9DF',
     'cc': 'GB',
     'city': 'Liverpool',
     'state': 'Liverpool',
     'country': 'United Kingdom',
     'formattedAddress': ['9-13 Berry St.',
      'Liverpool',
      'L1 9DF',
      'United Kingdom']},
    'categories': [{'id': '4bf58dd8d48988d145941735',
      'name': 'Chinese Restaurant',
      'pluralName': 'Chinese Restaurants',
      'shortName': 'Chinese',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/asian_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1565699909',
    'hasPerk': False},
   {'id': '4ba22649f964a52054df37e3',
    'name': 'Hondo Chinese Supermarket',
    'location': {'lat': 53.39924686153291,
     'lng': -2.9743337631225586,
     'labeledLatLngs': [{'label': 'display',
       'lat': 53.39924686153291,
       'lng': -2.9743337631225586}],
     'distance': 665,
     'cc': 'GB',
     'country': 'United Kingdom',
     'formattedAddress': ['United Kingdom']},
    'categories': [{'id': '4bf58dd8d48988d118951735',
      'name': 'Grocery Store',
      'pluralName': 'Grocery Stores',
      'shortName': 'Grocery Store',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/shops/food_grocery_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1565699909',
    'hasPerk': False},
   {'id': '50acff2f498e9668ba74b303',
    'name': 'Mabo Chinese restaurant',
    'location': {'lat': 53.399361059552774,
     'lng': -2.976775770739097,
     'labeledLatLngs': [{'label': 'display',
       'lat': 53.399361059552774,
       'lng': -2.976775770739097}],
     'distance': 824,
     'cc': 'GB',
     'country': 'United Kingdom',
     'formattedAddress': ['United Kingdom']},
    'categories': [{'id': '4bf58dd8d48988d145941735',
      'name': 'Chinese Restaurant',
      'pluralName': 'Chinese Restaurants',
      'shortName': 'Chinese',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/asian_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1565699909',
    'hasPerk': False},
   {'id': '53285222498e5a5ccd1df306',
    'name': 'SIDA Chinese Supermarket',
    'location': {'address': 'Bold St',
     'lat': 53.402070273114454,
     'lng': -2.976003242599527,
     'labeledLatLngs': [{'label': 'display',
       'lat': 53.402070273114454,
       'lng': -2.976003242599527}],
     'distance': 795,
     'cc': 'GB',
     'city': 'Liverpool',
     'state': 'Liverpool',
     'country': 'United Kingdom',
     'formattedAddress': ['Bold St', 'Liverpool', 'United Kingdom']},
    'categories': [{'id': '4bf58dd8d48988d1f9941735',
      'name': 'Food & Drink Shop',
      'pluralName': 'Food & Drink Shops',
      'shortName': 'Food & Drink',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/shops/foodanddrink_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1565699909',
    'hasPerk': False},
   {'id': '56a13df3498e05a14e96b16f',
    'name': 'favorite Chinese take away',
    'location': {'lat': 53.399204,
     'lng': -2.977068,
     'labeledLatLngs': [{'label': 'display',
       'lat': 53.399204,
       'lng': -2.977068}],
     'distance': 845,
     'cc': 'GB',
     'country': 'United Kingdom',
     'formattedAddress': ['United Kingdom']},
    'categories': [{'id': '4bf58dd8d48988d145941735',
      'name': 'Chinese Restaurant',
      'pluralName': 'Chinese Restaurants',
      'shortName': 'Chinese',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/asian_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1565699909',
    'hasPerk': False},
   {'id': '4cf033de7e93f04d4a9e4569',
    'name': 'Mr Chilli Chinese Restaurant',
    'location': {'address': '46-48 Mt Pleasant',
     'lat': 53.404192,
     'lng': -2.975556,
     'labeledLatLngs': [{'label': 'display',
       'lat': 53.404192,
       'lng': -2.975556}],
     'distance': 862,
     'postalCode': 'L3',
     'cc': 'GB',
     'city': 'Liverpool',
     'state': 'Liverpool',
     'country': 'United Kingdom',
     'formattedAddress': ['46-48 Mt Pleasant',
      'Liverpool',
      'L3',
      'United Kingdom']},
    'categories': [{'id': '4bf58dd8d48988d145941735',
      'name': 'Chinese Restaurant',
      'pluralName': 'Chinese Restaurants',
      'shortName': 'Chinese',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/asian_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1565699909',
    'hasPerk': False},
   {'id': '4ff05936e4b0a36f6f21ced1',
    'name': 'Liverpool Chinese Gospel Church',
    'location': {'lat': 53.397592,
     'lng': -2.978805,
     'labeledLatLngs': [{'label': 'display',
       'lat': 53.397592,
       'lng': -2.978805}],
     'distance': 996,
     'cc': 'GB',
     'country': 'United Kingdom',
     'formattedAddress': ['United Kingdom']},
    'categories': [{'id': '4bf58dd8d48988d132941735',
      'name': 'Church',
      'pluralName': 'Churches',
      'shortName': 'Church',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/building/religious_church_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1565699909',
    'hasPerk': False},
   {'id': '516beda3e4b0510f20faca98',
    'name': 'SIDA Chinese Supermarket',
    'location': {'address': 'London Road',
     'lat': 53.40979370945597,
     'lng': -2.9670264799851895,
     'labeledLatLngs': [{'label': 'display',
       'lat': 53.40979370945597,
       'lng': -2.9670264799851895}],
     'distance': 1083,
     'cc': 'GB',
     'city': 'Liverpool',
     'state': 'Liverpool',
     'country': 'United Kingdom',
     'formattedAddress': ['London Road', 'Liverpool', 'United Kingdom']},
    'categories': [{'id': '4bf58dd8d48988d118951735',
      'name': 'Grocery Store',
      'pluralName': 'Grocery Stores',
      'shortName': 'Grocery Store',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/shops/food_grocery_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1565699909',
    'hasPerk': False},
   {'id': '4bf7a2b75317a5932165fe7e',
    'name': 'Chung Wah Supermarket',
    'location': {'address': 'Hardy St',
     'lat': 53.397276265275266,
     'lng': -2.979604860415079,
     'labeledLatLngs': [{'label': 'display',
       'lat': 53.397276265275266,
       'lng': -2.979604860415079}],
     'distance': 1057,
     'postalCode': 'L1 5JN',
     'cc': 'GB',
     'city': 'Liverpool',
     'country': 'United Kingdom',
     'formattedAddress': ['Hardy St',
      'Liverpool',
      'L1 5JN',
      'United Kingdom']},
    'categories': [{'id': '4bf58dd8d48988d118951735',
      'name': 'Grocery Store',
      'pluralName': 'Grocery Stores',
      'shortName': 'Grocery Store',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/shops/food_grocery_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1565699909',
    'hasPerk': False},
   {'id': '4b69f018f964a52024bd2be3',
    'name': 'Mei Mei',
    'location': {'address': '9-13 Berry St',
     'crossStreet': 'Roscoe Ln',
     'lat': 53.40118718247768,
     'lng': -2.975978711959284,
     'labeledLatLngs': [{'label': 'display',
       'lat': 53.40118718247768,
       'lng': -2.975978711959284}],
     'distance': 774,
     'postalCode': 'L1 9DF',
     'cc': 'GB',
     'city': 'Liverpool',
     'country': 'United Kingdom',
     'formattedAddress': ['9-13 Berry St (Roscoe Ln)',
      'Liverpool',
      'L1 9DF',
      'United Kingdom']},
    'categories': [{'id': '4bf58dd8d48988d145941735',
      'name': 'Chinese Restaurant',
      'pluralName': 'Chinese Restaurants',
      'shortName': 'Chinese',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/asian_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1565699909',
    'hasPerk': False}]}}

In [19]:
# assign relevant part of JSON to venues
venues_l = results_l['response']['venues']

# tranform venues into a dataframe
dataframe_l = json_normalize(venues_l)
dataframe_l.head()

,id,name,categories,referralId,hasPerk,location.address,location.crossStreet,location.lat,location.lng,location.labeledLatLngs,location.distance,location.postalCode,location.cc,location.country,location.formattedAddress,location.city,location.state
0,544e9938498e020c02a65b06,Campus real Chinese restaurant,"[{'id': '4bf58dd8d48988d145941735', 'name': 'C...",v-1565699909,False,12 Myrtle Street,Liverpool,53.400970,-2.966229,"[{'label': 'display', 'lat': 53.40097, 'lng': ...",147,L7 7DP,GB,United Kingdom,"[12 Myrtle Street (Liverpool), L7 7DP, United ...",NaN,NaN
1,54198a46498efed5afdc5d80,Lida Chinese supermarket,"[{'id': '4d954b0ea243a5684a65b473', 'name': 'C...",v-1565699909,False,NaN,NaN,53.400806,-2.961559,"[{'label': 'display', 'lat': 53.4008062956977,...",203,NaN,GB,United Kingdom,[United Kingdom],NaN,NaN
2,4d9092e3d4ec8cfa1fb0a589,Arch Chinese Restaurant And Takeaway,"[{'id': '4bf58dd8d48988d145941735', 'name': 'C...",v-1565699909,False,9-13 Berry St.,NaN,53.400157,-2.976411,"[{'label': 'display', 'lat': 53.400157, 'lng':...",794,L1 9DF,GB,United Kingdom,"[9-13 Berry St., Liverpool, L1 9DF, United Kin...",Liverpool,Liverpool
3,4ba22649f964a52054df37e3,Hondo Chinese Supermarket,"[{'id': '4bf58dd8d48988d118951735', 'name': 'G...",v-1565699909,False,NaN,NaN,53.399247,-2.974334,"[{'label': 'display', 'lat': 53.39924686153291...",665,NaN,GB,United Kingdom,[United Kingdom],NaN,NaN
4,50acff2f498e9668ba74b303,Mabo Chinese restaurant,"[{'id': '4bf58dd8d48988d145941735', 'name': 'C...",v-1565699909,False,NaN,NaN,53.399361,-2.976776,"[{'label': 'display', 'lat': 53.39936105955277...",824,NaN,GB,United Kingdom,[United Kingdom],NaN,NaN

In [20]:
# keep only columns that include venue name, and anything that is associated with location
filtered_columns = ['name', 'categories'] + [col for col in dataframe_l.columns if col.startswith('location.')] + ['id']
dataframe_filtered = dataframe_l.loc[:, filtered_columns]

# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

# filter the category for each row
dataframe_filtered['categories'] = dataframe_filtered.apply(get_category_type, axis=1)

# clean column names by keeping only last term
dataframe_filtered.columns = [column.split('.')[-1] for column in dataframe_filtered.columns]

dataframe_filtered

,name,categories,address,crossStreet,lat,lng,labeledLatLngs,distance,postalCode,cc,country,formattedAddress,city,state,id
0,Campus real Chinese restaurant,Chinese Restaurant,12 Myrtle Street,Liverpool,53.400970,-2.966229,"[{'label': 'display', 'lat': 53.40097, 'lng': ...",147,L7 7DP,GB,United Kingdom,"[12 Myrtle Street (Liverpool), L7 7DP, United ...",NaN,NaN,544e9938498e020c02a65b06
1,Lida Chinese supermarket,Convenience Store,NaN,NaN,53.400806,-2.961559,"[{'label': 'display', 'lat': 53.4008062956977,...",203,NaN,GB,United Kingdom,[United Kingdom],NaN,NaN,54198a46498efed5afdc5d80
2,Arch Chinese Restaurant And Takeaway,Chinese Restaurant,9-13 Berry St.,NaN,53.400157,-2.976411,"[{'label': 'display', 'lat': 53.400157, 'lng':...",794,L1 9DF,GB,United Kingdom,"[9-13 Berry St., Liverpool, L1 9DF, United Kin...",Liverpool,Liverpool,4d9092e3d4ec8cfa1fb0a589
3,Hondo Chinese Supermarket,Grocery Store,NaN,NaN,53.399247,-2.974334,"[{'label': 'display', 'lat': 53.39924686153291...",665,NaN,GB,United Kingdom,[United Kingdom],NaN,NaN,4ba22649f964a52054df37e3
4,Mabo Chinese restaurant,Chinese Restaurant,NaN,NaN,53.399361,-2.976776,"[{'label': 'display', 'lat': 53.39936105955277...",824,NaN,GB,United Kingdom,[United Kingdom],NaN,NaN,50acff2f498e9668ba74b303
5,SIDA Chinese Supermarket,Food & Drink Shop,Bold St,NaN,53.402070,-2.976003,"[{'label': 'display', 'lat': 53.40207027311445...",795,NaN,GB,United Kingdom,"[Bold St, Liverpool, United Kingdom]",Liverpool,Liverpool,53285222498e5a5ccd1df306
6,favorite Chinese take away,Chinese Restaurant,NaN,NaN,53.399204,-2.977068,"[{'label': 'display', 'lat': 53.399204, 'lng':...",845,NaN,GB,United Kingdom,[United Kingdom],NaN,NaN,56a13df3498e05a14e96b16f
7,Mr Chilli Chinese Restaurant,Chinese Restaurant,46-48 Mt Pleasant,NaN,53.404192,-2.975556,"[{'label': 'display', 'lat': 53.404192, 'lng':...",862,L3,GB,United Kingdom,"[46-48 Mt Pleasant, Liverpool, L3, United King...",Liverpool,Liverpool,4cf033de7e93f04d4a9e4569
8,Liverpool Chinese Gospel Church,Church,NaN,NaN,53.397592,-2.978805,"[{'label': 'display', 'lat': 53.397592, 'lng':...",996,NaN,GB,United Kingdom,[United Kingdom],NaN,NaN,4ff05936e4b0a36f6f21ced1
9,SIDA Chinese Supermarket,Grocery Store,London Road,NaN,53.409794,-2.967026,"[{'label': 'display', 'lat': 53.40979370945597...",1083,NaN,GB,United Kingdom,"[London Road, Liverpool, United Kingdom]",Liverpool,Liverpool,516beda3e4b0510f20faca98
10,Chung Wah Supermarket,Grocery Store,Hardy St,NaN,53.397276,-2.979605,"[{'label': 'display', 'lat': 53.39727626527526...",1057,L1 5JN,GB,United Kingdom,"[Hardy St, Liverpool, L1 5JN, United Kingdom]",Liverpool,NaN,4bf7a2b75317a5932165fe7e
11,Mei Mei,Chinese Restaurant,9-13 Berry St,Roscoe Ln,53.401187,-2.975979,"[{'label': 'display', 'lat': 53.40118718247768...",774,L1 9DF,GB,United Kingdom,"[9-13 Berry St (Roscoe Ln), Liverpool, L1 9DF,...",Liverpool,NaN,4b69f018f964a52024bd2be3

In [21]:
dataframe_filtered.name

0           Campus real Chinese restaurant
1                 Lida Chinese supermarket
2     Arch Chinese Restaurant And Takeaway
3                Hondo Chinese Supermarket
4                  Mabo Chinese restaurant
5                 SIDA Chinese Supermarket
6               favorite Chinese take away
7             Mr Chilli Chinese Restaurant
8          Liverpool Chinese Gospel Church
9                 SIDA Chinese Supermarket
10                   Chung Wah Supermarket
11                                 Mei Mei
Name: name, dtype: object

In [22]:
venues_map = folium.Map(location=[latitude_l, longitude_l], zoom_start=13) # generate map centred around the Conrad Hotel

# add a red circle marker to represent the U of L
folium.features.CircleMarker(
    [latitude_l, longitude_l],
    radius=10,
    color='red',
    # popup='Mr Chilli',
    fill = True,
    fill_color = 'red',
    fill_opacity = 0.6
).add_to(venues_map)

# add the Italian restaurants as blue circle markers
for lat, lng, label in zip(dataframe_filtered.lat, dataframe_filtered.lng, dataframe_filtered.categories):
    folium.features.CircleMarker(
        [lat, lng],
        radius=5,
        color='blue',
        popup=label,
        fill = True,
        fill_color='blue',
        fill_opacity=0.6
    ).add_to(venues_map)

# display map
venues_map

##### Chinese restaurants around The University of Manchester

In [23]:
CLIENT_ID = '40TA5YCVA3CXTBIWMNPDMBKLDL4O4BVC5E4BFN5KXKMMKHL4' #  Foursquare ID
CLIENT_SECRET = 'OFICYUUXDQKDMPHZOTTNFIWVMK5EFL23DO1HPXN2SKZMBJZM' #  Foursquare Secret
VERSION = '20180604'
LIMIT = 30
print('My credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

My credentails:
CLIENT_ID: 40TA5YCVA3CXTBIWMNPDMBKLDL4O4BVC5E4BFN5KXKMMKHL4
CLIENT_SECRET:OFICYUUXDQKDMPHZOTTNFIWVMK5EFL23DO1HPXN2SKZMBJZM

In [24]:
address_m = 'Oxford Rd, Manchester M13 9PL'

geolocator_m = Nominatim(user_agent="foursquare_agent")
location_m = geolocator_m.geocode(address_m)
latitude_m = location_m.latitude
longitude_m = location_m.longitude
print(latitude_m, longitude_m)

53.4669225 -2.234321

In [25]:
search_query= 'Chinese'
radius = 1000
print(search_query + ' .... OK!')
url_m = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'.format(CLIENT_ID, CLIENT_SECRET, latitude_m, longitude_m, VERSION, search_query, radius, LIMIT)
url_m
results_m = requests.get(url_m).json()
results_m

Chinese .... OK!

{'meta': {'code': 200, 'requestId': '5d52af46ba9211002531c42e'},
 'response': {'venues': [{'id': '4ade0e19f964a520cb6e21e3',
    'name': 'Tai Pan Chinese Restaurant | 喜臨門大酒楼',
    'location': {'address': 'Brunswick House 81-97 Upper Brook St.',
     'lat': 53.46750336549708,
     'lng': -2.229680915813638,
     'labeledLatLngs': [{'label': 'display',
       'lat': 53.46750336549708,
       'lng': -2.229680915813638}],
     'distance': 314,
     'postalCode': 'M13 9TX',
     'cc': 'GB',
     'city': 'Manchester',
     'country': 'United Kingdom',
     'formattedAddress': ['Brunswick House 81-97 Upper Brook St.',
      'Manchester',
      'M13 9TX',
      'United Kingdom']},
    'categories': [{'id': '4bf58dd8d48988d145941735',
      'name': 'Chinese Restaurant',
      'pluralName': 'Chinese Restaurants',
      'shortName': 'Chinese',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/asian_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1565699910',
    'hasPerk': False},
   {'id': '4aef4a07f964a52043d721e3',
    'name': 'Red Chilli Chinese Restaurant | 红椒京川菜馆',
    'location': {'address': '403-419 Oxford Rd.',
     'lat': 53.46297481668661,
     'lng': -2.2299236196266707,
     'labeledLatLngs': [{'label': 'display',
       'lat': 53.46297481668661,
       'lng': -2.2299236196266707}],
     'distance': 527,
     'postalCode': 'M13 9WL',
     'cc': 'GB',
     'city': 'Manchester',
     'country': 'United Kingdom',
     'formattedAddress': ['403-419 Oxford Rd.',
      'Manchester',
      'M13 9WL',
      'United Kingdom']},
    'categories': [{'id': '4bf58dd8d48988d145941735',
      'name': 'Chinese Restaurant',
      'pluralName': 'Chinese Restaurants',
      'shortName': 'Chinese',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/asian_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1565699910',
    'hasPerk': False},
   {'id': '4ec02bfc61af06192b6e6825',
    'name': 'Azuma Chinese Restaurant',
    'location': {'address': '73 Cavendish St.',
     'lat': 53.46874339500669,
     'lng': -2.2418273772563078,
     'labeledLatLngs': [{'label': 'display',
       'lat': 53.46874339500669,
       'lng': -2.2418273772563078}],
     'distance': 537,
     'postalCode': 'M15 6BN',
     'cc': 'GB',
     'city': 'Manchester',
     'country': 'United Kingdom',
     'formattedAddress': ['73 Cavendish St.',
      'Manchester',
      'M15 6BN',
      'United Kingdom']},
    'categories': [{'id': '4bf58dd8d48988d145941735',
      'name': 'Chinese Restaurant',
      'pluralName': 'Chinese Restaurants',
      'shortName': 'Chinese',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/asian_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1565699910',
    'hasPerk': False},
   {'id': '4b6ac719f964a520e3df2be3',
    'name': 'Lameizi Chinese Supermarket & Restaurant',
    'location': {'address': 'Unit 2 The Quadrangle Chester St',
     'lat': 53.47224025486125,
     'lng': -2.2403104672618688,
     'labeledLatLngs': [{'label': 'display',
       'lat': 53.47224025486125,
       'lng': -2.2403104672618688}],
     'distance': 712,
     'postalCode': 'M1 5QS',
     'cc': 'GB',
     'city': 'Manchester',
     'country': 'United Kingdom',
     'formattedAddress': ['Unit 2 The Quadrangle Chester St',
      'Manchester',
      'M1 5QS',
      'United Kingdom']},
    'categories': [{'id': '4bf58dd8d48988d1f9941735',
      'name': 'Food & Drink Shop',
      'pluralName': 'Food & Drink Shops',
      'shortName': 'Food & Drink',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/shops/foodanddrink_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1565699910',
    'hasPerk': False},
   {'id': '4ce92a29d27560fc61aa983a',
    'name': 'Manchester Chinese Centre',
    'location': {'address': '67 Ardwick Green North',
     'lat': 53.47140574894196,
     'lng': -2.225006560818723,
     'labeledLatLngs': [{'label': 'display',
       'lat': 53.47140574894196,
       'lng': -2.225006560818723}],
     'distance': 793,
     'postalCode': 'M12 6FX',
     'cc': 'GB',
     'city': 'Manchester',
     'state': 'Greater Manchester',
     'country': 'United Kingdom',
     'formattedAddress': ['67 Ardwick Green North',
      'Manchester',
      'Greater Manchester',
      'M12 6FX',
      'United Kingdom']},
    'categories': [{'id': '4bf58dd8d48988d1a8941735',
      'name': 'General College & University',
      'pluralName': 'General Colleges & Universities',
      'shortName': 'Education',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/education/other_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1565699910',
    'hasPerk': False}]}}

In [26]:

# assign relevant part of JSON to venues
venues_m = results_m['response']['venues']

# tranform venues into a dataframe
dataframe_m = json_normalize(venues_m)
dataframe_m.head()

,id,name,categories,referralId,hasPerk,location.address,location.lat,location.lng,location.labeledLatLngs,location.distance,location.postalCode,location.cc,location.city,location.country,location.formattedAddress,location.state
0,4ade0e19f964a520cb6e21e3,Tai Pan Chinese Restaurant | 喜臨門大酒楼,"[{'id': '4bf58dd8d48988d145941735', 'name': 'C...",v-1565699910,False,Brunswick House 81-97 Upper Brook St.,53.467503,-2.229681,"[{'label': 'display', 'lat': 53.46750336549708...",314,M13 9TX,GB,Manchester,United Kingdom,"[Brunswick House 81-97 Upper Brook St., Manche...",NaN
1,4aef4a07f964a52043d721e3,Red Chilli Chinese Restaurant | 红椒京川菜馆,"[{'id': '4bf58dd8d48988d145941735', 'name': 'C...",v-1565699910,False,403-419 Oxford Rd.,53.462975,-2.229924,"[{'label': 'display', 'lat': 53.46297481668661...",527,M13 9WL,GB,Manchester,United Kingdom,"[403-419 Oxford Rd., Manchester, M13 9WL, Unit...",NaN
2,4ec02bfc61af06192b6e6825,Azuma Chinese Restaurant,"[{'id': '4bf58dd8d48988d145941735', 'name': 'C...",v-1565699910,False,73 Cavendish St.,53.468743,-2.241827,"[{'label': 'display', 'lat': 53.46874339500669...",537,M15 6BN,GB,Manchester,United Kingdom,"[73 Cavendish St., Manchester, M15 6BN, United...",NaN
3,4b6ac719f964a520e3df2be3,Lameizi Chinese Supermarket & Restaurant,"[{'id': '4bf58dd8d48988d1f9941735', 'name': 'F...",v-1565699910,False,Unit 2 The Quadrangle Chester St,53.472240,-2.240310,"[{'label': 'display', 'lat': 53.47224025486125...",712,M1 5QS,GB,Manchester,United Kingdom,"[Unit 2 The Quadrangle Chester St, Manchester,...",NaN
4,4ce92a29d27560fc61aa983a,Manchester Chinese Centre,"[{'id': '4bf58dd8d48988d1a8941735', 'name': 'G...",v-1565699910,False,67 Ardwick Green North,53.471406,-2.225007,"[{'label': 'display', 'lat': 53.47140574894196...",793,M12 6FX,GB,Manchester,United Kingdom,"[67 Ardwick Green North, Manchester, Greater M...",Greater Manchester

In [27]:
# keep only columns that include venue name, and anything that is associated with location
filtered_columns = ['name', 'categories'] + [col for col in dataframe_m.columns if col.startswith('location.')] + ['id']
dataframe_filtered = dataframe_m.loc[:, filtered_columns]

# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_mist = row['categories']
    except:
        categories_mist = row['venue.categories']
        
    if len(categories_mist) == 0:
        return None
    else:
        return categories_mist[0]['name']

# filter the category for each row
dataframe_filtered['categories'] = dataframe_filtered.apply(get_category_type, axis=1)

# clean column names by keeping only last term
dataframe_filtered.columns = [column.split('.')[-1] for column in dataframe_filtered.columns]

dataframe_filtered

dataframe_filtered.name

0         Tai Pan Chinese Restaurant | 喜臨門大酒楼
1      Red Chilli Chinese Restaurant | 红椒京川菜馆
2                    Azuma Chinese Restaurant
3    Lameizi Chinese Supermarket & Restaurant
4                   Manchester Chinese Centre
Name: name, dtype: object

In [28]:
venues_map = folium.Map(location=[latitude_m, longitude_m], zoom_start=13) # generate map centred around the Conrad Hotel

# add a red circle marker to represent the U of L
folium.features.CircleMarker(
    [latitude_m, longitude_m],
    radius=10,
    color='red',
    # popup='Mr Chilli',
    fill = True,
    fill_color = 'red',
    fill_opacity = 0.6
).add_to(venues_map)

# add the Italian restaurants as blue circle markers
for lat, lng, label in zip(dataframe_filtered.lat, dataframe_filtered.lng, dataframe_filtered.categories):
    folium.features.CircleMarker(
        [lat, lng],
        radius=5,
        color='blue',
        popup=label,
        fill = True,
        fill_color='blue',
        fill_opacity=0.6
    ).add_to(venues_map)

# display map
venues_map

## Let's check all venues around each area

In [29]:
# search_query= 'Chinese'
radius_m = 1000
LIMIT=100

address_m = 'Oxford Rd, Manchester M13 9PL'
geolocator_m = Nominatim(user_agent="foursquare_agent")
location_m = geolocator_m.geocode(address_m)
latitude_m = location_m.latitude
longitude_m = location_m.longitude
print(latitude_m, longitude_m)

#print(search_query + ' .... OK!')
url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    VERSION, 
    latitude_m, 
    longitude_m, 
    radius_m, 
    LIMIT)

results = requests.get(url).json()

#borrow the get_category_type function from the Foursquare lab.
# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

#clean the json and structure it into a pandas dataframe
venues = results['response']['groups'][0]['items']    
nearby_venues = json_normalize(venues) # flatten JSON

# filter columns
filtered_columns = ['venue.name','venue.location.postalCode', 'venue.categories', 'venue.location.lat', 'venue.location.lng']
nearby_venues =nearby_venues.loc[:, filtered_columns]

# filter the category for each row
nearby_venues['venue.categories'] = nearby_venues.apply(get_category_type, axis=1)

# clean columns
nearby_venues.columns = [col.split(".")[-1] for col in nearby_venues.columns]
nearby_venues['postcode']=nearby_venues['postalCode'].fillna("")
f = lambda x: x["postcode"].split(' ', 1)[0]
#reviews["disappointed"] = reviews.apply(f, axis=1)
nearby_venues['postcode']=nearby_venues.apply(f,axis=1)
print('{} venues were returned by Foursquare for The U of M.'.format(nearby_venues.shape[0]))
nearby_venues_m=nearby_venues
nearby_venues_m.head()

53.4669225 -2.234321
74 venues were returned by Foursquare for The U of M.

,name,postalCode,categories,lat,lng,postcode
0,Royal Northern College of Music (RNCM),M13 9RD,College Arts Building,53.468365,-2.236709,M13
1,Christie’s Bistro,M13 9PL,Café,53.465310,-2.233827,M13
2,The Manchester Museum,M13 9PL,Museum,53.466526,-2.234001,M13
3,Eighth Day Café (Eighth Day Co-op),M1 7DU,Vegetarian / Vegan Restaurant,53.471027,-2.237811,M1
4,Sandbar,M1 7HL,Bar,53.470669,-2.235885,M1

In [30]:
radius_l = 1000
LIMIT=100

address_l = 'Chatham St, Liverpool L69 7ZN'
geolocator_l = Nominatim(user_agent="foursquare_agent")
location_l = geolocator_l.geocode(address_l)
latitude_l = location_l.latitude
longitude_l = location_l.longitude
print(latitude_l, longitude_l)

#print(search_query + ' .... OK!')
url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    VERSION, 
    latitude_l, 
    longitude_l, 
    radius_l, 
    LIMIT)

results = requests.get(url).json()

#borrow the get_category_type function from the Foursquare lab.
# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

#clean the json and structure it into a pandas dataframe
venues = results['response']['groups'][0]['items']    
nearby_venues = json_normalize(venues) # flatten JSON

# filter columns
filtered_columns = ['venue.name','venue.location.postalCode', 'venue.categories', 'venue.location.lat', 'venue.location.lng']
nearby_venues =nearby_venues.loc[:, filtered_columns]

# filter the category for each row
nearby_venues['venue.categories'] = nearby_venues.apply(get_category_type, axis=1)

# clean columns
nearby_venues.columns = [col.split(".")[-1] for col in nearby_venues.columns]
nearby_venues['postcode']=nearby_venues['postalCode'].fillna("")
f = lambda x: x["postcode"].split(' ', 1)[0]
#reviews["disappointed"] = reviews.apply(f, axis=1)
nearby_venues['postcode']=nearby_venues.apply(f,axis=1)
print('{} venues were returned by Foursquare for The U of L.'.format(nearby_venues.shape[0]))
nearby_venues_l=nearby_venues
nearby_venues_l.head()

53.4001881 -2.9644371
87 venues were returned by Foursquare for The U of L.

,name,postalCode,categories,lat,lng,postcode
0,The Belvedere,L7 7EB,Bar,53.400209,-2.969568,L7
1,Free State Kitchen,L1 9DE,American Restaurant,53.402436,-2.970429,L1
2,Moose and Moonshine,L1 9BW,Café,53.400972,-2.970662,L1
3,Philharmonic Dining Rooms,L1 9BX,Pub,53.401645,-2.970363,L1
4,Hope Street Hotel,L1 9DA,Hotel,53.400943,-2.970766,L1

In [31]:
nearby_venues_m['postcode']=nearby_venues_m['postcode'].dropna()
venue_m=pd.merge(nearby_venues_m,df_m, on='postcode',how='left')
venue_m

,name,postalCode,categories,lat,lng,postcode,latitude,longitude,Post town,Coverage,Local authority area
0,Royal Northern College of Music (RNCM),M13 9RD,College Arts Building,53.468365,-2.236709,M13,53.46030,-2.21389,MANCHESTER,"Ardwick, Longsight, Chorlton-on-Medlock",Manchester
1,Christie’s Bistro,M13 9PL,Café,53.465310,-2.233827,M13,53.46030,-2.21389,MANCHESTER,"Ardwick, Longsight, Chorlton-on-Medlock",Manchester
2,The Manchester Museum,M13 9PL,Museum,53.466526,-2.234001,M13,53.46030,-2.21389,MANCHESTER,"Ardwick, Longsight, Chorlton-on-Medlock",Manchester
3,Eighth Day Café (Eighth Day Co-op),M1 7DU,Vegetarian / Vegan Restaurant,53.471027,-2.237811,M1,53.47734,-2.23508,MANCHESTER,"Piccadilly, City Centre, Market Street",Manchester
4,Sandbar,M1 7HL,Bar,53.470669,-2.235885,M1,53.47734,-2.23508,MANCHESTER,"Piccadilly, City Centre, Market Street",Manchester
5,Manchester Academy 3,M13 9PR,Music Venue,53.464280,-2.231852,M13,53.46030,-2.21389,MANCHESTER,"Ardwick, Longsight, Chorlton-on-Medlock",Manchester
6,Five Guys,M13,Burger Joint,53.467491,-2.235672,M13,53.46030,-2.21389,MANCHESTER,"Ardwick, Longsight, Chorlton-on-Medlock",Manchester
7,Tai Pan Chinese Restaurant | 喜臨門大酒楼,M13 9TX,Chinese Restaurant,53.467503,-2.229681,M13,53.46030,-2.21389,MANCHESTER,"Ardwick, Longsight, Chorlton-on-Medlock",Manchester
8,Archie's,M13 9NS,Fast Food Restaurant,53.470875,-2.237712,M13,53.46030,-2.21389,MANCHESTER,"Ardwick, Longsight, Chorlton-on-Medlock",Manchester
9,Öl Brewery Bar,M1 7ED,Brewery,53.471896,-2.238473,M1,53.47734,-2.23508,MANCHESTER,"Piccadilly, City Centre, Market Street",Manchester
10,Manchester Aquatics Centre,M13 9SS,Pool,53.469443,-2.235426,M13,53.46030,-2.21389,MANCHESTER,"Ardwick, Longsight, Chorlton-on-Medlock",Manchester
11,Takk Espresso Bar,M1 7ED,Café,53.471834,-2.238618,M1,53.47734,-2.23508,MANCHESTER,"Piccadilly, City Centre, Market Street",Manchester
12,Manchester Academy 2,M13 9PR,Music Venue,53.464386,-2.232262,M13,53.46030,-2.21389,MANCHESTER,"Ardwick, Longsight, Chorlton-on-Medlock",Manchester
13,Pret A Manger,M13 9RD,Sandwich Place,53.467950,-2.235369,M13,53.46030,-2.21389,MANCHESTER,"Ardwick, Longsight, Chorlton-on-Medlock",Manchester
14,Flour And Flagon,M1 7HL,Pub,53.470509,-2.236462,M1,53.47734,-2.23508,MANCHESTER,"Piccadilly, City Centre, Market Street",Manchester
15,Zouk Tea Bar & Grill,M1 5QS,Indian Restaurant,53.472321,-2.240544,M1,53.47734,-2.23508,MANCHESTER,"Piccadilly, City Centre, Market Street",Manchester
16,The Deaf Institute,M1 7HE,Bar,53.470289,-2.236569,M1,53.47734,-2.23508,MANCHESTER,"Piccadilly, City Centre, Market Street",Manchester
17,Costa Coffee,M1 5QA,Coffee Shop,53.472734,-2.239394,M1,53.47734,-2.23508,MANCHESTER,"Piccadilly, City Centre, Market Street",Manchester
18,Azuma Chinese Restaurant,M15 6BN,Chinese Restaurant,53.468743,-2.241827,M15,53.46563,-2.25008,MANCHESTER,"Hulme, Manchester Science Park, Old Trafford","Manchester, Trafford"
19,"Whitworth Art Gallery, University of Manchester",M15 6ER,Art Gallery,53.460354,-2.228674,M15,53.46563,-2.25008,MANCHESTER,"Hulme, Manchester Science Park, Old Trafford","Manchester, Trafford"
20,小樹林,M13 9LU,Chinese Restaurant,53.464586,-2.223287,M13,53.46030,-2.21389,MANCHESTER,"Ardwick, Longsight, Chorlton-on-Medlock",Manchester
21,Whitworth Park,M13 9WJ,Park,53.459259,-2.229967,M13,53.46030,-2.21389,MANCHESTER,"Ardwick, Longsight, Chorlton-on-Medlock",Manchester
22,Manchester Academy,M13 9PR,Music Venue,53.463796,-2.231212,M13,53.46030,-2.21389,MANCHESTER,"Ardwick, Longsight, Chorlton-on-Medlock",Manchester
23,Big Hands,M13 9NS,Bar,53.462960,-2.230403,M13,53.46030,-2.21389,MANCHESTER,"Ardwick, Longsight, Chorlton-on-Medlock",Manchester
24,Hatch,M1 7ED,Street Food Gathering,53.471972,-2.238277,M1,53.47734,-2.23508,MANCHESTER,"Piccadilly, City Centre, Market Street",Manchester
25,The Salisbury Ale House,M1 5NE,Pub,53.473969,-2.241055,M1,53.47734,-2.23508,MANCHESTER,"Piccadilly, City Centre, Market Street",Manchester
26,Palace Theatre,M1 6FT,Theater,53.474943,-2.241055,M1,53.47734,-2.23508,MANCHESTER,"Piccadilly, City Centre, Market Street",Manchester
27,Pancho's Burritos,M1 5QS,Burrito Place,53.472285,-2.240249,M1,53.47734,-2.23508,MANCHESTER,"Piccadilly, City Centre, Market Street",Manchester
28,Chimaek,M1,Korean Restaurant,53.472975,-2.240962,M1,53.47734,-2.23508,MANCHESTER,"Piccadilly, City Centre, Market Street",Manchester
29,Gorilla,M1 5WW,Bar,53.474341,-2.242592,M1,53.47734,-2.23508,MANCHESTER,"Piccadilly, City Centre, Market Street",Manchester
...,...,...,...,...,...,...,...,...,...,...,...
44,Grano,M15 5JH,Café,53.467739,-2.246914,M15,53.46563,-2.25008,MANCHESTER,"Hulme, Manchester Science Park, Old Trafford","Manchester, Trafford"
45,Java Bar Espresso,M1 5QA,Coffee Shop,53.474274,-2.241321,M1,53.47734,-2.23508,MANCHESTER,"Piccadilly, City Centre, Market Street",Manchester
46,Morrisons Manchester - Grafton Street,M13 9NU,Supermarket,53.463155,-2.229471,M13,53.46030,-2.21389,MANCHESTER,"Ardwick, Longsight, Chorlton-on-Medlock",Manchester
47,Ice Stone Gelato,NaN,Ice Cream Shop,53.470454,-2.237341,,NaN,NaN,NaN,NaN,NaN
48,WOOD,M15 4RA,Restaurant,53.472356,-2.245982,M15,53.46563,-2.25008,MANCHESTER,"Hulme, Manchester Science Park, Old Trafford","Manchester, Trafford"
49,Red Chilli Chinese Restaurant | 红椒京川菜馆,M13 9WL,Chinese Restaurant,53.462975,-2.229924,M13,53.46030,-2.21389,MANCHESTER,"Ardwick, Longsight, Chorlton-on-Medlock",Manchester
50,The Footage,M1 7DZ,Pub,53.470112,-2.236651,M1,53.47734,-2.23508,MANCHESTER,"Piccadilly, City Centre, Market Street",Manchester
51,Wex Photo Video,M12 6HH,Camera Store,53.473597,-2.228753,M12,53.46482,-2.20187,MANCHESTER,"Ardwick, Longsight, Chorlton-on-Medlock",Manchester
52,Ducie Arms,M15 6HS,Pub,53.463154,-2.234994,M15,53.46563,-2.25008,MANCHESTER,"Hulme, Manchester Science Park, Old Trafford","Manchester, Trafford"
53,The Turing Tap,M13 9WG,Pub,53.462535,-2.229269,M13,53.46030,-2.21389,MANCHESTER,"Ardwick, Longsight, Chorlton-on-Medlock",Manchester
54,Han Dynasty Manchester | 汉朝曼彻斯特店,M1 3NY,Chinese Restaurant,53.475674,-2.237566,M1,53.47734,-2.23508,MANCHESTER,"Piccadilly, City Centre, Market Street",Manchester
55,Joshua Brooks,M1 6NG,Pub,53.474241,-2.237386,M1,53.47734,-2.23508,MANCHESTER,"Piccadilly, City Centre, Market Street",Manchester
56,Trinity Sports Centre,M15 6HP,Recreation Center,53.465015,-2.239101,M15,53.46563,-2.25008,MANCHESTER,"Hulme, Manchester Science Park, Old Trafford","Manchester, Trafford"
57,M&S Simply Food,NaN,Grocery Store,53.460758,-2.226533,,NaN,NaN,NaN,NaN,NaN
58,Kim by the Sea,M15 5RF,Café,53.465311,-2.248516,M15,53.46563,-2.25008,MANCHESTER,"Hulme, Manchester Science Park, Old Trafford","Manchester, Trafford"
59,Ibis Hotel,M1 7DG,Hotel,53.474102,-2.236735,M1,53.47734,-2.23508,MANCHESTER,"Piccadilly, City Centre, Market Street",Manchester
60,Starbucks,M13 9NQ,Coffee Shop,53.461821,-2.228550,M13,53.46030,-2.21389,MANCHESTER,"Ardwick, Longsight, Chorlton-on-Medlock",Manchester
61,Sainsbury's Local,M13 9BL,Grocery Store,53.463312,-2.230056,M13,53.46030,-2.21389,MANCHESTER,"Ardwick, Longsight, Chorlton-on-Medlock",Manchester
62,Costa Coffee,M13 9NT,Coffee Shop,53.463042,-2.230115,M13,53.46030,-2.21389,MANCHESTER,"Ardwick, Longsight, Chorlton-on-Medlock",Manchester
63,Union Bar,M1 3 9,Bar,53.464366,-2.232389,M1,53.47734,-2.23508,MANCHESTER,"Piccadilly, City Centre, Market Street",Manchester
64,Asda,M15 5AS,Supermarket,53.461307,-2.246087,M15,53.46563,-2.25008,MANCHESTER,"Hulme, Manchester Science Park, Old Trafford","Manchester, Trafford"
65,Abdul's,M13 9NS,Middle Eastern Restaurant,53.463032,-2.230161,M13,53.46030,-2.21389,MANCHESTER,"Ardwick, Longsight, Chorlton-on-Medlock",Manchester
66,McColl's,NaN,Convenience Store,53.461658,-2.229276,,NaN,NaN,NaN,NaN,NaN
67,Manchester Pets & Aquatics,M12 6AL,Pet Store,53.468452,-2.221568,M12,53.46482,-2.20187,MANCHESTER,"Ardwick, Longsight, Chorlton-on-Medlock",Manchester
68,Tesco Express,M13 9XF,Grocery Store,53.470375,-2.223810,M13,53.46030,-2.21389,MANCHESTER,"Ardwick, Longsight, Chorlton-on-Medlock",Manchester
69,Apsley Cottage,M12 6AW,Pub,53.469258,-2.221682,M12,53.46482,-2.20187,MANCHESTER,"Ardwick, Longsight, Chorlton-on-Medlock",Manchester
70,Booker,NaN,Warehouse Store,53.467352,-2.220819,,NaN,NaN,NaN,NaN,NaN
71,LloydsPharmacy,NaN,Pharmacy,53.469899,-2.221578,,NaN,NaN,NaN,NaN,NaN
72,Elizabeth Gaskell House,M13 9LW,Museum,53.462785,-2.221913,M13,53.46030,-2.21389,MANCHESTER,"Ardwick, Longsight, Chorlton-on-Medlock",Manchester
73,Moss Side Swimming,NaN,Gym Pool,53.461510,-2.245961,,NaN,NaN,NaN,NaN,NaN

In [32]:
#check how many venues were returned for each area
print('There are {} uniques categories around UofM.'.format(len(venue_m['categories'].unique())))
venue_m.groupby('categories').count()

There are 38 uniques categories around UofM.

,name,postalCode,lat,lng,postcode,latitude,longitude,Post town,Coverage,Local authority area
categories,,,,,,,,,,
Art Gallery,1,1,1,1,1,1,1,1,1,1
Bakery,1,1,1,1,1,1,1,1,1,1
Bar,8,8,8,8,8,8,8,8,8,8
Brewery,1,1,1,1,1,1,1,1,1,1
Burger Joint,2,2,2,2,2,2,2,2,2,2
Burrito Place,1,1,1,1,1,1,1,1,1,1
Café,4,4,4,4,4,4,4,4,4,4
Camera Store,1,1,1,1,1,1,1,1,1,1
Chinese Restaurant,5,5,5,5,5,5,5,5,5,5
Cocktail Bar,1,1,1,1,1,1,1,1,1,1
Coffee Shop,5,5,5,5,5,5,5,5,5,5
College Arts Building,1,1,1,1,1,1,1,1,1,1
Concert Hall,1,1,1,1,1,1,1,1,1,1
Convenience Store,1,0,1,1,1,0,0,0,0,0
Fast Food Restaurant,1,1,1,1,1,1,1,1,1,1
Grocery Store,3,2,3,3,3,2,2,2,2,2
Gym Pool,1,0,1,1,1,0,0,0,0,0
Hotel,1,1,1,1,1,1,1,1,1,1
Ice Cream Shop,1,0,1,1,1,0,0,0,0,0
Indian Restaurant,2,2,2,2,2,2,2,2,2,2
Japanese Restaurant,1,1,1,1,1,1,1,1,1,1
Korean Restaurant,1,1,1,1,1,1,1,1,1,1
Middle Eastern Restaurant,1,1,1,1,1,1,1,1,1,1
Museum,2,2,2,2,2,2,2,2,2,2
Music Venue,3,3,3,3,3,3,3,3,3,3
Park,1,1,1,1,1,1,1,1,1,1
Pet Store,1,1,1,1,1,1,1,1,1,1
Pharmacy,1,0,1,1,1,0,0,0,0,0
Pool,1,1,1,1,1,1,1,1,1,1
Pub,8,8,8,8,8,8,8,8,8,8
Recreation Center,1,1,1,1,1,1,1,1,1,1
Restaurant,2,2,2,2,2,1,1,1,1,1
Sandwich Place,1,1,1,1,1,1,1,1,1,1
Street Food Gathering,1,1,1,1,1,1,1,1,1,1
Supermarket,3,3,3,3,3,3,3,3,3,3
Theater,2,2,2,2,2,2,2,2,2,2
Vegetarian / Vegan Restaurant,1,1,1,1,1,1,1,1,1,1
Warehouse Store,1,0,1,1,1,0,0,0,0,0

In [33]:
nearby_venues_l['postcode']=nearby_venues_l['postcode'].dropna()
venue_l=pd.merge(nearby_venues_l,df_l, on='postcode',how='left')
print(venue_l.head)

<bound method NDFrame.head of                          name postalCode              categories        lat  \
0               The Belvedere     L7 7EB                     Bar  53.400209
1          Free State Kitchen     L1 9DE     American Restaurant  53.402436
2         Moose and Moonshine     L1 9BW                    Café  53.400972
3   Philharmonic Dining Rooms     L1 9BX                     Pub  53.401645
4           Hope Street Hotel     L1 9DA                   Hotel  53.400943
..                        ...        ...                     ...        ...
82              Tesco Express     L3 5UB           Grocery Store  53.405850
83  Catherine street bus stop        NaN                Bus Stop  53.396741
84          Nightingale House     L8 1TG  Thrift / Vintage Store  53.395763
85             The Crypt Hall        NaN   General Entertainment  53.405809
86                   Fire Fit        NaN    Gym / Fitness Center  53.391606

         lng postcode  latitude  longitude  Post town  \
0  -2.969568       L7  53.40549   -2.94776  LIVERPOOL
1  -2.970429       L1  53.40254   -2.97928  LIVERPOOL
2  -2.970662       L1  53.40254   -2.97928  LIVERPOOL
3  -2.970363       L1  53.40254   -2.97928  LIVERPOOL
4  -2.970766       L1  53.40254   -2.97928  LIVERPOOL
..       ...      ...       ...        ...        ...
82 -2.967376       L3  53.40880   -2.98394  LIVERPOOL
83 -2.968132                NaN        NaN        NaN
84 -2.966101       L8  53.39009   -2.96246  LIVERPOOL
85 -2.968202                NaN        NaN        NaN
86 -2.967043                NaN        NaN        NaN

                                         Coverage Local authority area
0   City Centre, Edge Hill, Fairfield, Kensington            Liverpool
1                                     City Centre            Liverpool
2                                     City Centre            Liverpool
3                                     City Centre            Liverpool
4                                     City Centre            Liverpool
..                                            ...                  ...
82                 City Centre, Everton, Vauxhall            Liverpool
83                                            NaN                  NaN
84                   City Centre, Dingle, Toxteth            Liverpool
85                                            NaN                  NaN
86                                            NaN                  NaN

[87 rows x 11 columns]>

In [34]:
#check how many venues were returned for each area
print('There are {} uniques categories around UofM.'.format(len(venue_l['categories'].unique())))
venue_l.groupby('categories').count()

There are 52 uniques categories around UofM.

,name,postalCode,lat,lng,postcode,latitude,longitude,Post town,Coverage,Local authority area
categories,,,,,,,,,,
American Restaurant,2,2,2,2,2,2,2,2,2,2
Art Museum,1,1,1,1,1,1,1,1,1,1
Bagel Shop,1,1,1,1,1,1,1,1,1,1
Bakery,1,1,1,1,1,1,1,1,1,1
Bar,7,6,7,7,7,6,6,6,6,6
Beer Bar,1,1,1,1,1,1,1,1,1,1
Bistro,1,1,1,1,1,1,1,1,1,1
Bookstore,1,1,1,1,1,1,1,1,1,1
Bus Stop,1,0,1,1,1,0,0,0,0,0
Café,4,4,4,4,4,4,4,4,4,4
Chinese Restaurant,2,2,2,2,2,1,1,1,1,1
Church,2,2,2,2,2,2,2,2,2,2
Cocktail Bar,1,1,1,1,1,1,1,1,1,1
Coffee Shop,8,5,8,8,8,5,5,5,5,5
College Arts Building,1,1,1,1,1,1,1,1,1,1
Comic Shop,1,1,1,1,1,1,1,1,1,1
Concert Hall,1,1,1,1,1,1,1,1,1,1
Diner,2,0,2,2,2,0,0,0,0,0
Eastern European Restaurant,1,1,1,1,1,1,1,1,1,1
Falafel Restaurant,1,1,1,1,1,1,1,1,1,1
Fast Food Restaurant,1,1,1,1,1,1,1,1,1,1
Food & Drink Shop,1,1,1,1,1,1,1,1,1,1
Garden,1,0,1,1,1,0,0,0,0,0
General Entertainment,1,0,1,1,1,0,0,0,0,0
Grocery Store,3,2,3,3,3,2,2,2,2,2
Gym,1,1,1,1,1,1,1,1,1,1
Gym / Fitness Center,1,0,1,1,1,0,0,0,0,0
History Museum,1,1,1,1,1,1,1,1,1,1
Hostel,1,0,1,1,1,0,0,0,0,0
Hot Dog Joint,1,1,1,1,1,1,1,1,1,1
Hotel,1,1,1,1,1,1,1,1,1,1
Indian Restaurant,1,1,1,1,1,1,1,1,1,1
Indie Movie Theater,1,1,1,1,1,1,1,1,1,1
Italian Restaurant,2,2,2,2,2,2,2,2,2,2
Japanese Restaurant,1,1,1,1,1,1,1,1,1,1
Lounge,1,1,1,1,1,1,1,1,1,1
Mexican Restaurant,1,1,1,1,1,1,1,1,1,1
Middle Eastern Restaurant,1,1,1,1,1,1,1,1,1,1
Moroccan Restaurant,1,1,1,1,1,1,1,1,1,1
North Indian Restaurant,1,0,1,1,1,0,0,0,0,0
Park,1,1,1,1,1,1,1,1,1,1
Pizza Place,1,1,1,1,1,1,1,1,1,1
Plaza,1,0,1,1,1,0,0,0,0,0
Pub,10,9,10,10,10,9,9,9,9,9
Restaurant,3,2,3,3,3,2,2,2,2,2
Sandwich Place,2,1,2,2,2,1,1,1,1,1
Seafood Restaurant,1,1,1,1,1,1,1,1,1,1
Spanish Restaurant,1,0,1,1,1,0,0,0,0,0
Steakhouse,1,0,1,1,1,0,0,0,0,0
Theater,1,1,1,1,1,1,1,1,1,1
Thrift / Vintage Store,1,1,1,1,1,1,1,1,1,1
Vegetarian / Vegan Restaurant,1,1,1,1,1,1,1,1,1,1

## Comparison of the venues of the two cities

In [35]:
df_m.head(5)
df_m=df_m[df_m.latitude !=0 ]
df_m

,postcode,latitude,longitude,Post town,Coverage,Local authority area
0,M1,53.477340,-2.235080,MANCHESTER,"Piccadilly, City Centre, Market Street",Manchester
1,M11,53.478340,-2.179330,MANCHESTER,"Clayton, Openshaw, Beswick",Manchester
2,M12,53.464820,-2.201870,MANCHESTER,"Ardwick, Longsight, Chorlton-on-Medlock",Manchester
3,M13,53.460300,-2.213890,MANCHESTER,"Ardwick, Longsight, Chorlton-on-Medlock",Manchester
4,M14,53.447700,-2.224370,MANCHESTER,"Fallowfield, Moss Side, Ladybarn, Rusholme, Lo...",Manchester
5,M15,53.465630,-2.250080,MANCHESTER,"Hulme, Manchester Science Park, Old Trafford","Manchester, Trafford"
6,M16,53.454810,-2.263570,MANCHESTER,"Firswood, Old Trafford, Whalley Range, Moss Side","Manchester, Trafford"
7,M17,53.469060,-2.317890,MANCHESTER,"Trafford Park, The Trafford Centre",Trafford
8,M18,53.461270,-2.168710,MANCHESTER,"Abbey Hey, Gorton",Manchester
9,M19,53.436960,-2.194210,MANCHESTER,"Levenshulme, Burnage","Manchester, Stockport"
10,M2,53.480030,-2.242630,MANCHESTER,"Deansgate, City Centre",Manchester
11,M20,53.425210,-2.230270,MANCHESTER,"Didsbury, Withington",Manchester
12,M21,53.437710,-2.270990,MANCHESTER,"Chorlton-cum-Hardy, Barlow Moor",Manchester
13,M22,53.385600,-2.258630,MANCHESTER,"Wythenshawe, Northenden, Sharston Industrial Area",Manchester
14,M23,53.399020,-2.287290,MANCHESTER,"Baguley, Brooklands (Manchester and Trafford),...","Manchester, Trafford"
15,M24,53.551130,-2.196240,MANCHESTER,"Middleton, Alkrington, Chadderton","Rochdale, Oldham"
16,M25,53.528500,-2.274590,MANCHESTER,"Prestwich, Sedgley Park, Simister",Bury
17,M26,53.561610,-2.333690,MANCHESTER,"Radcliffe, Stoneclough","Bury, Bolton"
18,M27,53.512160,-2.336310,MANCHESTER,"Swinton, Clifton, Pendlebury, Wardley, Agecroft",Salford
19,M28,53.514670,-2.396660,MANCHESTER,"Worsley, Walkden, Boothstown, Mosley Common, W...","Salford, Wigan"
20,M29,53.508160,-2.456920,MANCHESTER,"Tyldesley, Astley",Wigan
21,M30,53.484240,-2.354180,MANCHESTER,"Eccles, Monton, Peel Green, Winton, Patricroft...",Salford
22,M31,53.419300,-2.421360,MANCHESTER,"Carrington, Partington",Trafford
23,M32,53.450210,-2.308720,MANCHESTER,"Stretford, Trafford Park",Trafford
24,M33,53.420500,-2.325060,SALE,"Sale, Brooklands (Manchester and Trafford)","Trafford, Manchester"
25,M34,53.455940,-2.117480,MANCHESTER,"Denton, Audenshaw",Tameside
26,M35,53.507140,-2.152300,MANCHESTER,Failsworth,Oldham
27,M38,53.531670,-2.420960,MANCHESTER,Little Hulton,Salford
28,M4,53.484550,-2.229090,MANCHESTER,"Ancoats, Northern Quarter, Strangeways",Manchester
29,M40,53.503490,-2.189990,MANCHESTER,"Collyhurst, Miles Platting, Moston, New Moston...",Manchester
30,M41,53.450950,-2.362940,MANCHESTER,"Urmston, Davyhulme, Flixton, Trafford Park",Trafford
31,M43,53.483780,-2.147700,MANCHESTER,Droylsden,Tameside
32,M44,53.440860,-2.426090,MANCHESTER,"Irlam, Cadishead",Salford
33,M45,53.547340,-2.288290,MANCHESTER,Whitefield,Bury
34,M46,53.526010,-2.490310,MANCHESTER,Atherton,Wigan
35,M5,53.479030,-2.284820,SALFORD,"Ordsall, Seedley, Weaste, University",Salford
36,M6,53.491590,-2.296960,SALFORD,"Pendleton, Irlams o' th' Height, Langworthy, S...",Salford
37,M7,53.505160,-2.260860,SALFORD,"Higher Broughton, Cheetwood, Lower Broughton, ...",Salford
38,M8,53.508800,-2.238270,MANCHESTER,"Crumpsall, Cheetham Hill",Manchester
39,M9,53.521430,-2.212690,MANCHESTER,"Harpurhey, Blackley",Manchester
40,M90,53.363090,-2.276530,MANCHESTER,Manchester Airport,Manchester
41,M50,53.479393,-2.304275,SALFORD,"Salford Quays, MediaCityUK",Salford
42,M99,53.484512,-2.234866,MANCHESTER,Manchester X; JD Williams (located geographica...,Manchester

In [36]:
df_l.head(5)
df_l=df_l[df_l.latitude !=0 ]
df_l

,postcode,latitude,longitude,Post town,Coverage,Local authority area
0,L1,53.402540,-2.979280,LIVERPOOL,City Centre,Liverpool
1,L10,53.473980,-2.926680,LIVERPOOL,"Aintree Village, Fazakerley","Sefton, Liverpool, Knowsley"
2,L11,53.448010,-2.914070,LIVERPOOL,"Clubmoor, Croxteth, Gillmoss, Norris Green",Liverpool
3,L12,53.434670,-2.894210,LIVERPOOL,"Croxteth Park, West Derby",Liverpool
4,L13,53.417400,-2.919430,LIVERPOOL,"Clubmoor, Old Swan, Stoneycroft, Tuebrook",Liverpool
5,L14,53.418610,-2.878830,LIVERPOOL,"Broadgreen, Dovecot, Knotty Ash, Page Moss","Liverpool, Knowsley"
6,L15,53.397630,-2.919010,LIVERPOOL,Wavertree,Liverpool
7,L16,53.398760,-2.887440,LIVERPOOL,"Broadgreen, Bowring Park, Childwall","Liverpool, Knowsley"
8,L17,53.377690,-2.939620,LIVERPOOL,"Aigburth, St Michael's Hamlet, Sefton Park",Liverpool
9,L18,53.380640,-2.906610,LIVERPOOL,"Allerton, Mossley Hill",Liverpool
10,L19,53.359100,-2.901650,LIVERPOOL,"Garston, Grassendale, Aigburth,",Liverpool
11,L2,53.406960,-2.988410,LIVERPOOL,City Centre,Liverpool
12,L20,53.452810,-2.987970,BOOTLE,"Bootle, Orrell","Sefton, Liverpool"
13,L20,53.452810,-2.987970,LIVERPOOL,Kirkdale,Liverpool
14,L21,53.470700,-2.998930,LIVERPOOL,"Ford, Litherland, Seaforth","Sefton, Liverpool"
15,L22,53.476760,-3.026200,LIVERPOOL,Waterloo,Sefton
16,L23,53.491180,-3.022030,LIVERPOOL,"Blundellsands, Brighton-le-Sands, Crosby, Litt...",Sefton
17,L24,53.343390,-2.836720,LIVERPOOL,"Hale, Speke","Halton, Liverpool"
18,L25,53.378270,-2.862960,LIVERPOOL,"Belle Vale, Gateacre, Hunts Cross, Woolton, Ha...","Liverpool, Knowsley"
19,L26,53.364100,-2.832620,LIVERPOOL,Halewood,"Liverpool, Knowsley"
20,L27,53.387440,-2.837580,LIVERPOOL,Netherley,Liverpool
21,L28,53.434900,-2.864110,LIVERPOOL,Stockbridge Village,"Liverpool, Knowsley"
22,L29,53.506790,-2.983190,LIVERPOOL,"Lunt, Sefton Village",Sefton
23,L3,53.408800,-2.983940,LIVERPOOL,"City Centre, Everton, Vauxhall",Liverpool
24,L30,53.484420,-2.970620,BOOTLE,"Bootle, Netherton",Sefton
25,L31,53.513460,-2.936590,LIVERPOOL,"Maghull, Lydiate, Melling, Waddicar",Sefton
26,L32,53.477860,-2.889090,LIVERPOOL,Kirkby,Knowsley
27,L33,53.489650,-2.875770,LIVERPOOL,Kirkby,Knowsley
28,L34,53.436140,-2.814450,PRESCOT,"Prescot, Knowsley Village",Knowsley
29,L35,53.414780,-2.782440,PRESCOT,"Prescot, Whiston, Rainhill","Knowsley, St Helens"
30,L36,53.414390,-2.839620,LIVERPOOL,"Huyton, Roby, Tarbock",Knowsley
31,L37,53.557350,-3.062880,LIVERPOOL,"Formby, Little Altcar, Great Altcar","Sefton, West Lancashire"
32,L38,53.524200,-3.049980,LIVERPOOL,"Ince Blundell, Hightown","Sefton, West Lancashire"
33,L39,53.561420,-2.895370,ORMSKIRK,"Ormskirk, Aughton",West Lancashire
34,L4,53.437750,-2.960520,LIVERPOOL,"Anfield, Kirkdale, Walton",Liverpool
35,L40,53.602270,-2.840320,ORMSKIRK,"Burscough, Mawdesley, Scarisbrick, Rufford, Ho...","West Lancashire, Chorley"
36,L5,53.425050,-2.975290,LIVERPOOL,"Anfield, Everton, Kirkdale, Vauxhall",Liverpool
37,L6,53.418960,-2.949560,LIVERPOOL,"Anfield, City Centre, Everton, Fairfield, Kens...",Liverpool
38,L69,53.407090,-2.973370,LIVERPOOL,"PO boxes in central Liverpool, government depa...",non-geographic
39,L7,53.405490,-2.947760,LIVERPOOL,"City Centre, Edge Hill, Fairfield, Kensington",Liverpool
40,L70,53.408910,-2.970400,LIVERPOOL,seasonal response mail[4],non-geographic
41,L8,53.390090,-2.962460,LIVERPOOL,"City Centre, Dingle, Toxteth",Liverpool
42,L9,53.461200,-2.952010,LIVERPOOL,"Aintree, Fazakerley, Orrell Park, Walton","Liverpool, Sefton"
43,L67,53.428970,-2.958583,LIVERPOOL,Littlewoods Pools[4],non-geographic
44,L68,53.473055,-2.960690,LIVERPOOL,Vernons Pools[4],non-geographic
45,L71,53.439492,-2.971429,LIVERPOOL,American Express[4],non-geographic
46,L72,53.480300,-2.988368,LIVERPOOL,Littlewoods[4],non-geographic
47,L73,53.406399,-2.975554,LIVERPOOL,"BT Group, large Selectapost users[4]",non-geographic
48,L74,53.393801,-2.988061,LIVERPOOL,HM Revenue and Customs (Customs and Excise)[4],non-geographic
49,L75,53.438613,-2.985222,LIVERPOOL,HM Revenue and Customs (Inland Revenue)[4],non-geographic

In [37]:
LIMIT=100


def getNearbyVenues(names, latitudes, longitudes, radius=500):
    
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
            
        # make the GET request
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Area', 
                  'Area Latitude', 
                  'Area Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

#run the above function on each neighborhood and create a new dataframe
m_venues = getNearbyVenues(names=df_m['Coverage'],
                                   latitudes=df_m['latitude'],
                                   longitudes=df_m['longitude']
                                  )

#check the size of the resulting dataframe
print(m_venues.shape)
m_venues.head()

Piccadilly, City Centre, Market Street
Clayton, Openshaw, Beswick
Ardwick, Longsight, Chorlton-on-Medlock
Ardwick, Longsight, Chorlton-on-Medlock
Fallowfield, Moss Side, Ladybarn, Rusholme, Longsight
Hulme, Manchester Science Park, Old Trafford
Firswood, Old Trafford, Whalley Range, Moss Side
Trafford Park, The Trafford Centre
Abbey Hey, Gorton
Levenshulme, Burnage
Deansgate, City Centre
Didsbury, Withington
Chorlton-cum-Hardy, Barlow Moor
Wythenshawe, Northenden, Sharston Industrial Area
Baguley, Brooklands (Manchester and Trafford), Roundthorn Industrial Estate
Middleton, Alkrington, Chadderton
Prestwich, Sedgley Park, Simister
Radcliffe, Stoneclough
Swinton, Clifton, Pendlebury, Wardley, Agecroft
Worsley, Walkden, Boothstown, Mosley Common, Wardley Industrial Estate
Tyldesley, Astley
Eccles, Monton, Peel Green, Winton, Patricroft, Barton-upon-Irwell, Ellesmere Park
Carrington, Partington
Stretford, Trafford Park
Sale, Brooklands (Manchester and Trafford)
Denton, Audenshaw
Failsworth
Little Hulton
Ancoats, Northern Quarter, Strangeways
Collyhurst, Miles Platting, Moston, New Moston, Newton Heath
Urmston, Davyhulme, Flixton, Trafford Park
Droylsden
Irlam, Cadishead
Whitefield
Atherton
Ordsall, Seedley, Weaste, University
Pendleton, Irlams o' th' Height, Langworthy, Seedley, Charlestown
Higher Broughton, Cheetwood, Lower Broughton, Kersal
Crumpsall, Cheetham Hill
Harpurhey, Blackley
Manchester Airport
Salford Quays, MediaCityUK
Manchester X; JD Williams (located geographically in M1 and M3)
(630, 7)

,Area,Area Latitude,Area Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
0,"Piccadilly, City Centre, Market Street",53.47734,-2.23508,The Molly House,53.477325,-2.237201,Pub
1,"Piccadilly, City Centre, Market Street",53.47734,-2.23508,Richmond Tea Rooms,53.477652,-2.236810,Tea Room
2,"Piccadilly, City Centre, Market Street",53.47734,-2.23508,Holiday Inn Manchester - City Centre,53.479058,-2.234100,Hotel
3,"Piccadilly, City Centre, Market Street",53.47734,-2.23508,Alan Turing Memorial Statue,53.476690,-2.236049,Monument / Landmark
4,"Piccadilly, City Centre, Market Street",53.47734,-2.23508,Hotel Motel One Manchester-Piccadilly,53.477407,-2.232318,Hotel

In [38]:
#check how many venues were returned for each area
print('There are {} uniques categories of Manchester.'.format(len(m_venues['Venue Category'].unique())))
m_venues.groupby('Venue Category').count()

There are 143 uniques categories of Manchester.

,Area,Area Latitude,Area Longitude,Venue,Venue Latitude,Venue Longitude
Venue Category,,,,,,
Adult Boutique,1,1,1,1,1,1
Airport,1,1,1,1,1,1
Airport Lounge,2,2,2,2,2,2
Airport Service,1,1,1,1,1,1
American Restaurant,6,6,6,6,6,6
Antique Shop,1,1,1,1,1,1
Art Gallery,4,4,4,4,4,4
Arts & Crafts Store,4,4,4,4,4,4
Asian Restaurant,7,7,7,7,7,7
Australian Restaurant,1,1,1,1,1,1
Auto Garage,2,2,2,2,2,2
BBQ Joint,2,2,2,2,2,2
Bakery,7,7,7,7,7,7
Bar,38,38,38,38,38,38
Bed & Breakfast,1,1,1,1,1,1
Beer Bar,10,10,10,10,10,10
Beer Store,2,2,2,2,2,2
Bike Shop,1,1,1,1,1,1
Bookstore,10,10,10,10,10,10
Brazilian Restaurant,3,3,3,3,3,3
Brewery,2,2,2,2,2,2
Bubble Tea Shop,3,3,3,3,3,3
Building,1,1,1,1,1,1
Burger Joint,7,7,7,7,7,7
Burrito Place,2,2,2,2,2,2
Bus Station,2,2,2,2,2,2
Bus Stop,5,5,5,5,5,5
Café,13,13,13,13,13,13
Caribbean Restaurant,3,3,3,3,3,3
Casino,1,1,1,1,1,1
...,...,...,...,...,...,...
Sculpture Garden,1,1,1,1,1,1
Shopping Plaza,1,1,1,1,1,1
Soccer Field,1,1,1,1,1,1
Soccer Stadium,1,1,1,1,1,1
Soup Place,2,2,2,2,2,2
Spanish Restaurant,2,2,2,2,2,2
Speakeasy,3,3,3,3,3,3
Sporting Goods Shop,3,3,3,3,3,3
Sports Bar,1,1,1,1,1,1
Sports Club,2,2,2,2,2,2
Stadium,1,1,1,1,1,1
Stationery Store,1,1,1,1,1,1
Steakhouse,6,6,6,6,6,6
Supermarket,18,18,18,18,18,18
Sushi Restaurant,5,5,5,5,5,5
Taco Place,1,1,1,1,1,1
Tanning Salon,1,1,1,1,1,1
Tapas Restaurant,1,1,1,1,1,1
Tea Room,10,10,10,10,10,10
Tennis Court,1,1,1,1,1,1
Thai Restaurant,5,5,5,5,5,5
Theater,2,2,2,2,2,2
Train Station,2,2,2,2,2,2
Tram Station,8,8,8,8,8,8
Vegetarian / Vegan Restaurant,4,4,4,4,4,4
Vietnamese Restaurant,2,2,2,2,2,2
Warehouse Store,2,2,2,2,2,2
Whisky Bar,1,1,1,1,1,1
Wine Bar,2,2,2,2,2,2
Yoga Studio,1,1,1,1,1,1

In [39]:
#check how many venues were returned for each area
print('There are {} uniques categories of Manchester.'.format(len(m_venues['Venue Category'].unique())))
m_venues.groupby('Area').count()

There are 143 uniques categories of Manchester.

,Area Latitude,Area Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
Area,,,,,,
"Abbey Hey, Gorton",7,7,7,7,7,7
"Ancoats, Northern Quarter, Strangeways",86,86,86,86,86,86
"Ardwick, Longsight, Chorlton-on-Medlock",7,7,7,7,7,7
Atherton,8,8,8,8,8,8
"Baguley, Brooklands (Manchester and Trafford), Roundthorn Industrial Estate",4,4,4,4,4,4
"Carrington, Partington",3,3,3,3,3,3
"Chorlton-cum-Hardy, Barlow Moor",16,16,16,16,16,16
"Clayton, Openshaw, Beswick",1,1,1,1,1,1
"Collyhurst, Miles Platting, Moston, New Moston, Newton Heath",4,4,4,4,4,4
"Crumpsall, Cheetham Hill",8,8,8,8,8,8
"Deansgate, City Centre",100,100,100,100,100,100
"Denton, Audenshaw",16,16,16,16,16,16
"Didsbury, Withington",11,11,11,11,11,11
Droylsden,5,5,5,5,5,5
"Eccles, Monton, Peel Green, Winton, Patricroft, Barton-upon-Irwell, Ellesmere Park",7,7,7,7,7,7
Failsworth,5,5,5,5,5,5
"Fallowfield, Moss Side, Ladybarn, Rusholme, Longsight",8,8,8,8,8,8
"Firswood, Old Trafford, Whalley Range, Moss Side",4,4,4,4,4,4
"Harpurhey, Blackley",5,5,5,5,5,5
"Higher Broughton, Cheetwood, Lower Broughton, Kersal",4,4,4,4,4,4
"Hulme, Manchester Science Park, Old Trafford",12,12,12,12,12,12
"Irlam, Cadishead",6,6,6,6,6,6
"Levenshulme, Burnage",5,5,5,5,5,5
Little Hulton,3,3,3,3,3,3
Manchester Airport,27,27,27,27,27,27
Manchester X; JD Williams (located geographically in M1 and M3),100,100,100,100,100,100
"Middleton, Alkrington, Chadderton",4,4,4,4,4,4
"Ordsall, Seedley, Weaste, University",5,5,5,5,5,5
"Pendleton, Irlams o' th' Height, Langworthy, Seedley, Charlestown",1,1,1,1,1,1
"Piccadilly, City Centre, Market Street",100,100,100,100,100,100
"Prestwich, Sedgley Park, Simister",4,4,4,4,4,4
"Radcliffe, Stoneclough",6,6,6,6,6,6
"Sale, Brooklands (Manchester and Trafford)",20,20,20,20,20,20
"Salford Quays, MediaCityUK",3,3,3,3,3,3
"Stretford, Trafford Park",3,3,3,3,3,3
"Swinton, Clifton, Pendlebury, Wardley, Agecroft",6,6,6,6,6,6
"Trafford Park, The Trafford Centre",1,1,1,1,1,1
"Tyldesley, Astley",1,1,1,1,1,1
"Urmston, Davyhulme, Flixton, Trafford Park",4,4,4,4,4,4
Whitefield,4,4,4,4,4,4
"Worsley, Walkden, Boothstown, Mosley Common, Wardley Industrial Estate",2,2,2,2,2,2
"Wythenshawe, Northenden, Sharston Industrial Area",4,4,4,4,4,4

In [40]:
#run the above function on each neighborhood and create a new dataframe
l_venues = getNearbyVenues(names=df_l['Coverage'],
                                   latitudes=df_l['latitude'],
                                   longitudes=df_l['longitude']
                                  )

#check the size of the resulting dataframe
print(l_venues.shape)
l_venues.head()

City Centre
Aintree Village, Fazakerley
Clubmoor, Croxteth, Gillmoss, Norris Green
Croxteth Park, West Derby
Clubmoor, Old Swan, Stoneycroft, Tuebrook
Broadgreen, Dovecot, Knotty Ash, Page Moss
Wavertree
Broadgreen, Bowring Park, Childwall
Aigburth, St Michael's Hamlet, Sefton Park
Allerton, Mossley Hill
Garston, Grassendale, Aigburth,
City Centre
Bootle, Orrell
Kirkdale
Ford, Litherland, Seaforth
Waterloo
Blundellsands, Brighton-le-Sands, Crosby, Little Crosby, Thornton
Hale, Speke
Belle Vale, Gateacre, Hunts Cross, Woolton, Halewood
Halewood
Netherley
Stockbridge Village
Lunt, Sefton Village
City Centre, Everton, Vauxhall
Bootle, Netherton
Maghull, Lydiate, Melling, Waddicar
Kirkby
Kirkby
Prescot, Knowsley Village
Prescot, Whiston, Rainhill
Huyton, Roby, Tarbock
Formby, Little Altcar, Great Altcar
Ince Blundell, Hightown
Ormskirk, Aughton
Anfield, Kirkdale, Walton
Burscough, Mawdesley, Scarisbrick, Rufford, Holmeswood
Anfield, Everton, Kirkdale, Vauxhall
Anfield, City Centre, Everton, Fairfield, Kensington, Tuebrook
PO boxes in central Liverpool, government departments in Liverpool and Bootle, University of Liverpool[4]
City Centre, Edge Hill, Fairfield, Kensington
seasonal response mail[4]
City Centre, Dingle, Toxteth
Aintree, Fazakerley, Orrell Park, Walton
Littlewoods Pools[4]
Vernons Pools[4]
American Express[4]
Littlewoods[4]
BT Group, large Selectapost users[4]
HM Revenue and Customs (Customs and Excise)[4]
HM Revenue and Customs (Inland Revenue)[4]
(698, 7)

,Area,Area Latitude,Area Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
0,City Centre,53.40254,-2.97928,Kazimier Garden,53.402805,-2.981879,Beer Garden
1,City Centre,53.40254,-2.97928,Leaf,53.402869,-2.977708,Café
2,City Centre,53.40254,-2.97928,Elif,53.403523,-2.979076,Turkish Restaurant
3,City Centre,53.40254,-2.97928,Mowgli Street Food,53.402828,-2.977600,Indian Restaurant
4,City Centre,53.40254,-2.97928,Bold Street Coffee,53.402394,-2.976993,Coffee Shop

In [41]:
#check how many venues were returned for each area
print('There are {} uniques categories of Liverpool.'.format(len(l_venues['Venue Category'].unique())))
l_venues.groupby('Venue Category').count()

There are 143 uniques categories of Liverpool.

,Area,Area Latitude,Area Longitude,Venue,Venue Latitude,Venue Longitude
Venue Category,,,,,,
American Restaurant,8,8,8,8,8,8
Argentinian Restaurant,1,1,1,1,1,1
Art Gallery,5,5,5,5,5,5
Art Museum,2,2,2,2,2,2
Arts & Crafts Store,1,1,1,1,1,1
Asian Restaurant,2,2,2,2,2,2
Athletics & Sports,2,2,2,2,2,2
BBQ Joint,1,1,1,1,1,1
Bagel Shop,1,1,1,1,1,1
Bakery,5,5,5,5,5,5
Bank,2,2,2,2,2,2
Bar,22,22,22,22,22,22
Bed & Breakfast,1,1,1,1,1,1
Beer Bar,4,4,4,4,4,4
Beer Garden,2,2,2,2,2,2
Bookstore,7,7,7,7,7,7
Botanical Garden,1,1,1,1,1,1
Brazilian Restaurant,3,3,3,3,3,3
Breakfast Spot,4,4,4,4,4,4
Brewery,2,2,2,2,2,2
Bridal Shop,1,1,1,1,1,1
Buffet,1,1,1,1,1,1
Burger Joint,8,8,8,8,8,8
Burrito Place,2,2,2,2,2,2
Bus Station,1,1,1,1,1,1
Bus Stop,3,3,3,3,3,3
Business Service,1,1,1,1,1,1
Café,25,25,25,25,25,25
Caribbean Restaurant,4,4,4,4,4,4
Chinese Restaurant,5,5,5,5,5,5
...,...,...,...,...,...,...
Sandwich Place,20,20,20,20,20,20
Scenic Lookout,4,4,4,4,4,4
Seafood Restaurant,3,3,3,3,3,3
Shopping Mall,5,5,5,5,5,5
Shopping Plaza,2,2,2,2,2,2
Soccer Field,6,6,6,6,6,6
Soccer Stadium,5,5,5,5,5,5
Souvenir Shop,1,1,1,1,1,1
Spanish Restaurant,4,4,4,4,4,4
Sporting Goods Shop,8,8,8,8,8,8
Sports Club,1,1,1,1,1,1
Stadium,2,2,2,2,2,2
Stationery Store,2,2,2,2,2,2
Steakhouse,2,2,2,2,2,2
Supermarket,17,17,17,17,17,17
Sushi Restaurant,1,1,1,1,1,1
Tapas Restaurant,5,5,5,5,5,5
Tea Room,5,5,5,5,5,5
Thai Restaurant,1,1,1,1,1,1
Theater,10,10,10,10,10,10
Thrift / Vintage Store,3,3,3,3,3,3
Toy / Game Store,1,1,1,1,1,1
Track,1,1,1,1,1,1
Train Station,11,11,11,11,11,11
Turkish Restaurant,2,2,2,2,2,2
Vegetarian / Vegan Restaurant,3,3,3,3,3,3
Video Game Store,4,4,4,4,4,4
Warehouse Store,3,3,3,3,3,3
Zoo,1,1,1,1,1,1
Zoo Exhibit,3,3,3,3,3,3

In [42]:
#check how many venues were returned for each area
print('There are {} uniques categories of Liverpool.'.format(len(l_venues['Venue Category'].unique())))
l_venues.groupby('Area').count()

There are 143 uniques categories of Liverpool.

,Area Latitude,Area Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
Area,,,,,,
"Aigburth, St Michael's Hamlet, Sefton Park",4,4,4,4,4,4
"Aintree Village, Fazakerley",1,1,1,1,1,1
"Aintree, Fazakerley, Orrell Park, Walton",5,5,5,5,5,5
"Allerton, Mossley Hill",7,7,7,7,7,7
American Express[4],15,15,15,15,15,15
"Anfield, City Centre, Everton, Fairfield, Kensington, Tuebrook",3,3,3,3,3,3
"Anfield, Everton, Kirkdale, Vauxhall",5,5,5,5,5,5
"Anfield, Kirkdale, Walton",6,6,6,6,6,6
"BT Group, large Selectapost users[4]",65,65,65,65,65,65
"Belle Vale, Gateacre, Hunts Cross, Woolton, Halewood",5,5,5,5,5,5
"Blundellsands, Brighton-le-Sands, Crosby, Little Crosby, Thornton",11,11,11,11,11,11
"Bootle, Netherton",10,10,10,10,10,10
"Bootle, Orrell",17,17,17,17,17,17
"Broadgreen, Bowring Park, Childwall",2,2,2,2,2,2
"Broadgreen, Dovecot, Knotty Ash, Page Moss",4,4,4,4,4,4
"Burscough, Mawdesley, Scarisbrick, Rufford, Holmeswood",9,9,9,9,9,9
City Centre,193,193,193,193,193,193
"City Centre, Dingle, Toxteth",4,4,4,4,4,4
"City Centre, Edge Hill, Fairfield, Kensington",5,5,5,5,5,5
"City Centre, Everton, Vauxhall",96,96,96,96,96,96
"Clubmoor, Croxteth, Gillmoss, Norris Green",1,1,1,1,1,1
"Clubmoor, Old Swan, Stoneycroft, Tuebrook",4,4,4,4,4,4
"Croxteth Park, West Derby",4,4,4,4,4,4
"Ford, Litherland, Seaforth",5,5,5,5,5,5
"Formby, Little Altcar, Great Altcar",10,10,10,10,10,10
"Garston, Grassendale, Aigburth,",6,6,6,6,6,6
HM Revenue and Customs (Customs and Excise)[4],15,15,15,15,15,15
HM Revenue and Customs (Inland Revenue)[4],6,6,6,6,6,6
"Hale, Speke",4,4,4,4,4,4
Halewood,5,5,5,5,5,5
"Huyton, Roby, Tarbock",9,9,9,9,9,9
"Ince Blundell, Hightown",4,4,4,4,4,4
Kirkby,5,5,5,5,5,5
Kirkdale,17,17,17,17,17,17
Littlewoods Pools[4],16,16,16,16,16,16
Littlewoods[4],2,2,2,2,2,2
"Maghull, Lydiate, Melling, Waddicar",4,4,4,4,4,4
Netherley,5,5,5,5,5,5
"Ormskirk, Aughton",2,2,2,2,2,2
"PO boxes in central Liverpool, government departments in Liverpool and Bootle, University of Liverpool[4]",46,46,46,46,46,46
"Prescot, Knowsley Village",6,6,6,6,6,6
Stockbridge Village,3,3,3,3,3,3
Vernons Pools[4],6,6,6,6,6,6
Waterloo,12,12,12,12,12,12
Wavertree,8,8,8,8,8,8
seasonal response mail[4],26,26,26,26,26,26

# Analyze Manchester

In [43]:

# one hot encoding
m_onehot = pd.get_dummies(m_venues[['Venue Category']], prefix="", prefix_sep="")

# add neighborhood column back to dataframe
m_onehot['Area'] = m_venues['Area'] 

# move neighborhood column to the first column
fixed_columns = [m_onehot.columns[-1]] + list(m_onehot.columns[:-1])
m_onehot = m_onehot[fixed_columns]

#examine the new dataframe size after one hot encoding
print('{} rows were returned after one hot encoding.'.format(m_onehot.shape[0]))

#group rows by neighborhood and by taking the mean of the frequency of occurrence of each category
m_grouped = m_onehot.groupby('Area').mean().reset_index()

#examine the new dataframe size after one hot encoding
print('{} rows were returned after grouping.'.format(m_grouped.shape[0]))

630 rows were returned after one hot encoding.
42 rows were returned after grouping.

In [44]:

#print each neighborhood along with the top 5 most common venues
num_top_venues = 5

for hood in m_grouped['Area']:
    print("----"+hood+"----")
    temp = m_grouped[m_grouped['Area'] == hood].T.reset_index()
    temp.columns = ['venue','freq']
    temp = temp.iloc[1:]
    temp['freq'] = temp['freq'].astype(float)
    temp = temp.round({'freq': 2})
    print(temp.sort_values('freq', ascending=False).reset_index(drop=True).head(num_top_venues))
    print('\n')

----Abbey Hey, Gorton----
                  venue  freq
0  Gym / Fitness Center  0.29
1                 Hotel  0.14
2                   Gym  0.14
3           Supermarket  0.14
4        Sandwich Place  0.14


----Ancoats, Northern Quarter, Strangeways----
          venue  freq
0           Bar  0.14
1   Coffee Shop  0.12
2           Pub  0.06
3  Cocktail Bar  0.05
4      Tea Room  0.05


----Ardwick, Longsight, Chorlton-on-Medlock----
               venue  freq
0  College Cafeteria  0.14
1  Convenience Store  0.14
2           Pharmacy  0.14
3       Liquor Store  0.14
4   Asian Restaurant  0.14


----Atherton----
              venue  freq
0       Supermarket  0.25
1               Pub  0.12
2       Roller Rink  0.12
3    Sandwich Place  0.12
4  Department Store  0.12


----Baguley, Brooklands (Manchester and Trafford), Roundthorn Industrial Estate----
                  venue  freq
0                  Park  0.50
1  Fast Food Restaurant  0.25
2          Tram Station  0.25
3              Pie Shop  0.00
4          Outlet Store  0.00


----Carrington, Partington----
               venue  freq
0  Convenience Store  0.33
1       Antique Shop  0.33
2      Grocery Store  0.33
3     Adult Boutique  0.00
4        Pizza Place  0.00


----Chorlton-cum-Hardy, Barlow Moor----
                 venue  freq
0        Grocery Store  0.12
1          Yoga Studio  0.06
2                  Bar  0.06
3  Japanese Restaurant  0.06
4       Cosmetics Shop  0.06


----Clayton, Openshaw, Beswick----
                   venue  freq
0      Indian Restaurant   1.0
1        Piercing Parlor   0.0
2   Pakistani Restaurant   0.0
3                   Park   0.0
4  Performing Arts Venue   0.0


----Collyhurst, Miles Platting, Moston, New Moston, Newton Heath----
            venue  freq
0            Café  0.25
1             Pub  0.25
2    Tram Station  0.25
3        Bus Stop  0.25
4  Adult Boutique  0.00


----Crumpsall, Cheetham Hill----
                       venue  freq
0                 Restaurant  0.12
1               Tram Station  0.12
2                       Park  0.12
3  Middle Eastern Restaurant  0.12
4              Grocery Store  0.12


----Deansgate, City Centre----
                venue  freq
0         Coffee Shop  0.08
1  Italian Restaurant  0.06
2          Steakhouse  0.05
3               Hotel  0.05
4    Asian Restaurant  0.04


----Denton, Audenshaw----
                venue  freq
0   Mobile Phone Shop  0.12
1      Clothing Store  0.12
2            Pharmacy  0.12
3         Supermarket  0.12
4  Italian Restaurant  0.06


----Didsbury, Withington----
           venue  freq
0    Pizza Place  0.18
1   Tennis Court  0.09
2       Wine Bar  0.09
3    Bus Station  0.09
4  Deli / Bodega  0.09


----Droylsden----
                venue  freq
0                 Pub   0.2
1         Supermarket   0.2
2  Chinese Restaurant   0.2
3            Pharmacy   0.2
4      Soccer Stadium   0.2


----Eccles, Monton, Peel Green, Winton, Patricroft, Barton-upon-Irwell, Ellesmere Park----
            venue  freq
0     Auto Garage  0.14
1             Gym  0.14
2     Pizza Place  0.14
3  Sandwich Place  0.14
4   Train Station  0.14


----Failsworth----
                        venue  freq
0                 Supermarket   0.2
1  Construction & Landscaping   0.2
2                         Pub   0.2
3        Gym / Fitness Center   0.2
4                      Bakery   0.2


----Fallowfield, Moss Side, Ladybarn, Rusholme, Longsight----
                  venue  freq
0  Gym / Fitness Center  0.25
1                  Park  0.12
2             Racetrack  0.12
3           Coffee Shop  0.12
4           Bus Station  0.12


----Firswood, Old Trafford, Whalley Range, Moss Side----
             venue  freq
0    Grocery Store  0.50
1   Sandwich Place  0.25
2         Bus Stop  0.25
3   Adult Boutique  0.00
4  Piercing Parlor  0.00


----Harpurhey, Blackley----
               venue  freq
0  Fish & Chips Shop   0.2
1              Hotel   0.2
2                Pub   0.2
3               Park   0.2
4                Bar   0.2


----Higher Broughton, Cheetwood, Lower Broughton, Kersal----
         venue  freq
0        River  0.25
1       Bakery  0.25
2     Bus Stop  0.25
3  Supermarket  0.25
4    Jazz Club  0.00


----Hulme, Manchester Science Park, Old Trafford----
                   venue  freq
0                   Café  0.17
1          Grocery Store  0.17
2                   Park  0.08
3      Convenience Store  0.08
4  Performing Arts Venue  0.08


----Irlam, Cadishead----
             venue  freq
0      Supermarket  0.33
1      Gas Station  0.17
2  Warehouse Store  0.17
3             Park  0.17
4              Gym  0.17


----Levenshulme, Burnage----
                  venue  freq
0            Restaurant   0.2
1      Indoor Play Area   0.2
2  Pakistani Restaurant   0.2
3  Gym / Fitness Center   0.2
4                  Park   0.2


----Little Hulton----
               venue  freq
0   Department Store  0.33
1  Convenience Store  0.33
2   Asian Restaurant  0.33
3        Pizza Place  0.00
4               Park  0.00


----Manchester Airport----
            venue  freq
0     Coffee Shop  0.22
1  Sandwich Place  0.07
2  Airport Lounge  0.07
3           Hotel  0.07
4  Duty-free Shop  0.07


----Manchester X; JD Williams (located geographically in M1 and M3)----
         venue  freq
0          Bar  0.11
1          Pub  0.07
2  Coffee Shop  0.07
3         Café  0.04
4     Tea Room  0.04


----Middleton, Alkrington, Chadderton----
            venue  freq
0             Pub  0.25
1     Supermarket  0.25
2   Grocery Store  0.25
3         Stadium  0.25
4  Adult Boutique  0.00


----Ordsall, Seedley, Weaste, University----
               venue  freq
0        Pizza Place   0.2
1  Indian Restaurant   0.2
2           Building   0.2
3         Food Truck   0.2
4            Brewery   0.2


----Pendleton, Irlams o' th' Height, Langworthy, Seedley, Charlestown----
                  venue  freq
0           Supermarket   1.0
1           Music Venue   0.0
2          Outlet Store   0.0
3  Pakistani Restaurant   0.0
4                  Park   0.0


----Piccadilly, City Centre, Market Street----
         venue  freq
0        Hotel  0.13
1      Gay Bar  0.11
2          Bar  0.07
3          Pub  0.06
4  Coffee Shop  0.04


----Prestwich, Sedgley Park, Simister----
                  venue  freq
0                  Park  0.50
1           Coffee Shop  0.25
2                   Pub  0.25
3       Piercing Parlor  0.00
4  Pakistani Restaurant  0.00


----Radcliffe, Stoneclough----
                    venue  freq
0                     Pub  0.33
1                    Pool  0.33
2  Furniture / Home Store  0.17
3    Fast Food Restaurant  0.17
4          Adult Boutique  0.00


----Sale, Brooklands (Manchester and Trafford)----
                venue  freq
0                 Pub  0.15
1       Grocery Store  0.10
2         Supermarket  0.10
3  Chinese Restaurant  0.10
4         Pizza Place  0.10


----Salford Quays, MediaCityUK----
            venue  freq
0             Bar  0.33
1    Tram Station  0.33
2         Brewery  0.33
3  Adult Boutique  0.00
4        Pie Shop  0.00


----Stretford, Trafford Park----
                  venue  freq
0       Warehouse Store  0.33
1  Gym / Fitness Center  0.33
2                  Park  0.33
3        Adult Boutique  0.00
4              Pie Shop  0.00


----Swinton, Clifton, Pendlebury, Wardley, Agecroft----
          venue  freq
0   Supermarket  0.50
1   Pizza Place  0.33
2          Park  0.17
3      Pie Shop  0.00
4  Outlet Store  0.00


----Trafford Park, The Trafford Centre----
                  venue  freq
0        Sandwich Place   1.0
1        Adult Boutique   0.0
2       Piercing Parlor   0.0
3  Pakistani Restaurant   0.0
4                  Park   0.0


----Tyldesley, Astley----
                  venue  freq
0         Grocery Store   1.0
1        Adult Boutique   0.0
2       Piercing Parlor   0.0
3  Pakistani Restaurant   0.0
4                  Park   0.0


----Urmston, Davyhulme, Flixton, Trafford Park----
                venue  freq
0  Italian Restaurant  0.25
1   Convenience Store  0.25
2        Dance Studio  0.25
3          Playground  0.25
4      Adult Boutique  0.00


----Whitefield----
                  venue  freq
0     Indian Restaurant  0.50
1                Bakery  0.25
2  Fast Food Restaurant  0.25
3   Japanese Restaurant  0.00
4           Pizza Place  0.00


----Worsley, Walkden, Boothstown, Mosley Common, Wardley Industrial Estate----
                  venue  freq
0           Sports Club   0.5
1                  Park   0.5
2        Adult Boutique   0.0
3           Record Shop   0.0
4  Pakistani Restaurant   0.0


----Wythenshawe, Northenden, Sharston Industrial Area----
            venue  freq
0    Tram Station  0.50
1     Coffee Shop  0.25
2     Supermarket  0.25
3  Adult Boutique  0.00
4        Pie Shop  0.00

In [45]:
#put into a pandas dataframe

#write a function to sort the venues in descending order
def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    
    return row_categories_sorted.index.values[0:num_top_venues]

#create the new dataframe and display the top 10 venues for each neighborhood
num_top_venues = 8

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['Area']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
areas_venues_sorted = pd.DataFrame(columns=columns)
areas_venues_sorted['Area'] = m_grouped['Area']

for ind in np.arange(m_grouped.shape[0]):
    areas_venues_sorted.iloc[ind, 1:] = return_most_common_venues(m_grouped.iloc[ind, :], num_top_venues)

areas_venues_sorted.head()

,Area,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue
0,"Abbey Hey, Gorton",Gym / Fitness Center,Hotel,Gym,Supermarket,Sandwich Place,Market,Deli / Bodega,Donut Shop
1,"Ancoats, Northern Quarter, Strangeways",Bar,Coffee Shop,Pub,Cocktail Bar,Tea Room,Bookstore,Record Shop,Beer Bar
2,"Ardwick, Longsight, Chorlton-on-Medlock",College Cafeteria,Asian Restaurant,Park,Liquor Store,Bus Stop,Pharmacy,Convenience Store,Cosmetics Shop
3,Atherton,Supermarket,Sandwich Place,Pub,Department Store,Bar,Roller Rink,Soccer Field,Dance Studio
4,"Baguley, Brooklands (Manchester and Trafford),...",Park,Fast Food Restaurant,Tram Station,Yoga Studio,Deli / Bodega,Duty-free Shop,Donut Shop,Dive Bar

In [52]:
m_merged = df_m
m_merged.rename(columns={'Coverage':'Area'}, inplace=True)

m_merged=m_merged.join(areas_venues_sorted.set_index('Area'),on='Area')
m_merged.head()

,postcode,latitude,longitude,Post town,Area,Local authority area,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue
0,M1,53.47734,-2.23508,MANCHESTER,"Piccadilly, City Centre, Market Street",Manchester,Hotel,Gay Bar,Bar,Pub,Coffee Shop,Cocktail Bar,Sushi Restaurant,Indian Restaurant
1,M11,53.47834,-2.17933,MANCHESTER,"Clayton, Openshaw, Beswick",Manchester,Indian Restaurant,Yoga Studio,Deli / Bodega,Electronics Store,Duty-free Shop,Donut Shop,Dive Bar,Discount Store
2,M12,53.46482,-2.20187,MANCHESTER,"Ardwick, Longsight, Chorlton-on-Medlock",Manchester,College Cafeteria,Asian Restaurant,Park,Liquor Store,Bus Stop,Pharmacy,Convenience Store,Cosmetics Shop
3,M13,53.46030,-2.21389,MANCHESTER,"Ardwick, Longsight, Chorlton-on-Medlock",Manchester,College Cafeteria,Asian Restaurant,Park,Liquor Store,Bus Stop,Pharmacy,Convenience Store,Cosmetics Shop
4,M14,53.44770,-2.22437,MANCHESTER,"Fallowfield, Moss Side, Ladybarn, Rusholme, Lo...",Manchester,Gym / Fitness Center,Bed & Breakfast,Fried Chicken Joint,Park,Racetrack,Bus Station,Coffee Shop,Art Gallery

In [47]:
m_grouped_clustering = m_grouped.drop('Area', 1)
m_grouped_clustering

,Adult Boutique,Airport,Airport Lounge,Airport Service,American Restaurant,Antique Shop,Art Gallery,Arts & Crafts Store,Asian Restaurant,Australian Restaurant,...,Thai Restaurant,Theater,Train Station,Tram Station,Vegetarian / Vegan Restaurant,Vietnamese Restaurant,Warehouse Store,Whisky Bar,Wine Bar,Yoga Studio
0,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.00,...,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.0000
1,0.00,0.000000,0.000000,0.000000,0.023256,0.000000,0.00,0.023256,0.000000,0.00,...,0.000000,0.00,0.000000,0.000000,0.011628,0.00,0.000000,0.011628,0.000000,0.0000
2,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.142857,0.00,...,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.0000
3,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.00,...,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.0000
4,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.00,...,0.000000,0.00,0.000000,0.250000,0.000000,0.00,0.000000,0.000000,0.000000,0.0000
5,0.00,0.000000,0.000000,0.000000,0.000000,0.333333,0.00,0.000000,0.000000,0.00,...,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.0000
6,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.00,...,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.0625
7,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.00,...,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.0000
8,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.00,...,0.000000,0.00,0.000000,0.250000,0.000000,0.00,0.000000,0.000000,0.000000,0.0000
9,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.125000,0.00,...,0.000000,0.00,0.000000,0.125000,0.000000,0.00,0.000000,0.000000,0.000000,0.0000
10,0.00,0.000000,0.000000,0.000000,0.010000,0.000000,0.02,0.000000,0.040000,0.01,...,0.030000,0.01,0.000000,0.000000,0.000000,0.01,0.000000,0.000000,0.010000,0.0000
11,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.00,...,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.0000
12,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.00,...,0.090909,0.00,0.000000,0.090909,0.000000,0.00,0.000000,0.000000,0.090909,0.0000
13,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.00,...,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.0000
14,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.00,...,0.000000,0.00,0.142857,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.0000
15,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.00,...,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.0000
16,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.00,...,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.0000
17,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.00,...,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.0000
18,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.00,...,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.0000
19,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.00,...,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.0000
20,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.00,...,0.000000,0.00,0.000000,0.000000,0.083333,0.00,0.000000,0.000000,0.000000,0.0000
21,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.00,...,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.166667,0.000000,0.000000,0.0000
22,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.00,...,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.0000
23,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.333333,0.00,...,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.0000
24,0.00,0.037037,0.074074,0.037037,0.000000,0.000000,0.00,0.000000,0.000000,0.00,...,0.000000,0.00,0.037037,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.0000
25,0.00,0.000000,0.000000,0.000000,0.020000,0.000000,0.00,0.020000,0.000000,0.00,...,0.000000,0.00,0.000000,0.000000,0.020000,0.00,0.000000,0.000000,0.000000,0.0000
26,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.00,...,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.0000
27,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.00,...,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.0000
28,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.00,...,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.0000
29,0.01,0.000000,0.000000,0.000000,0.010000,0.000000,0.02,0.000000,0.000000,0.00,...,0.010000,0.01,0.000000,0.000000,0.000000,0.01,0.000000,0.000000,0.000000,0.0000
30,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.00,...,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.0000
31,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.00,...,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.0000
32,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.00,...,0.000000,0.00,0.000000,0.050000,0.000000,0.00,0.000000,0.000000,0.000000,0.0000
33,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.00,...,0.000000,0.00,0.000000,0.333333,0.000000,0.00,0.000000,0.000000,0.000000,0.0000
34,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.00,...,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.333333,0.000000,0.000000,0.0000
35,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.00,...,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.0000
36,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.00,...,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.0000
37,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.00,...,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.0000
38,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.00,...,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.0000
39,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.00,...,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.0000
40,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.00,...,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.0000
41,0.00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.00,...,0.000000,0.00,0.000000,0.500000,0.000000,0.00,0.000000,0.000000,0.000000,0.0000

In [58]:
m_merged

,postcode,latitude,longitude,Post town,Area,Local authority area,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue
0,M1,53.477340,-2.235080,MANCHESTER,"Piccadilly, City Centre, Market Street",Manchester,Hotel,Gay Bar,Bar,Pub,Coffee Shop,Cocktail Bar,Sushi Restaurant,Indian Restaurant
1,M11,53.478340,-2.179330,MANCHESTER,"Clayton, Openshaw, Beswick",Manchester,Indian Restaurant,Yoga Studio,Deli / Bodega,Electronics Store,Duty-free Shop,Donut Shop,Dive Bar,Discount Store
2,M12,53.464820,-2.201870,MANCHESTER,"Ardwick, Longsight, Chorlton-on-Medlock",Manchester,College Cafeteria,Asian Restaurant,Park,Liquor Store,Bus Stop,Pharmacy,Convenience Store,Cosmetics Shop
3,M13,53.460300,-2.213890,MANCHESTER,"Ardwick, Longsight, Chorlton-on-Medlock",Manchester,College Cafeteria,Asian Restaurant,Park,Liquor Store,Bus Stop,Pharmacy,Convenience Store,Cosmetics Shop
4,M14,53.447700,-2.224370,MANCHESTER,"Fallowfield, Moss Side, Ladybarn, Rusholme, Lo...",Manchester,Gym / Fitness Center,Bed & Breakfast,Fried Chicken Joint,Park,Racetrack,Bus Station,Coffee Shop,Art Gallery
5,M15,53.465630,-2.250080,MANCHESTER,"Hulme, Manchester Science Park, Old Trafford","Manchester, Trafford",Café,Grocery Store,Deli / Bodega,Discount Store,Vegetarian / Vegan Restaurant,Park,Convenience Store,Fast Food Restaurant
6,M16,53.454810,-2.263570,MANCHESTER,"Firswood, Old Trafford, Whalley Range, Moss Side","Manchester, Trafford",Grocery Store,Bus Stop,Sandwich Place,Yoga Studio,Duty-free Shop,Donut Shop,Dive Bar,Discount Store
7,M17,53.469060,-2.317890,MANCHESTER,"Trafford Park, The Trafford Centre",Trafford,Sandwich Place,Yoga Studio,Deli / Bodega,Electronics Store,Duty-free Shop,Donut Shop,Dive Bar,Discount Store
8,M18,53.461270,-2.168710,MANCHESTER,"Abbey Hey, Gorton",Manchester,Gym / Fitness Center,Hotel,Gym,Supermarket,Sandwich Place,Market,Deli / Bodega,Donut Shop
9,M19,53.436960,-2.194210,MANCHESTER,"Levenshulme, Burnage","Manchester, Stockport",Gym / Fitness Center,Restaurant,Indoor Play Area,Pakistani Restaurant,Park,Deli / Bodega,Donut Shop,Dive Bar
10,M2,53.480030,-2.242630,MANCHESTER,"Deansgate, City Centre",Manchester,Coffee Shop,Italian Restaurant,Steakhouse,Hotel,Asian Restaurant,Pub,Plaza,Thai Restaurant
11,M20,53.425210,-2.230270,MANCHESTER,"Didsbury, Withington",Manchester,Pizza Place,Bus Station,Wine Bar,Gym / Fitness Center,Tram Station,Thai Restaurant,Tennis Court,Deli / Bodega
12,M21,53.437710,-2.270990,MANCHESTER,"Chorlton-cum-Hardy, Barlow Moor",Manchester,Grocery Store,Bar,Indian Restaurant,Gas Station,Japanese Restaurant,Falafel Restaurant,Fabric Shop,Music Venue
13,M22,53.385600,-2.258630,MANCHESTER,"Wythenshawe, Northenden, Sharston Industrial Area",Manchester,Tram Station,Coffee Shop,Supermarket,Dance Studio,Duty-free Shop,Donut Shop,Dive Bar,Discount Store
14,M23,53.399020,-2.287290,MANCHESTER,"Baguley, Brooklands (Manchester and Trafford),...","Manchester, Trafford",Park,Fast Food Restaurant,Tram Station,Yoga Studio,Deli / Bodega,Duty-free Shop,Donut Shop,Dive Bar
15,M24,53.551130,-2.196240,MANCHESTER,"Middleton, Alkrington, Chadderton","Rochdale, Oldham",Stadium,Pub,Grocery Store,Supermarket,Deli / Bodega,Duty-free Shop,Donut Shop,Dive Bar
16,M25,53.528500,-2.274590,MANCHESTER,"Prestwich, Sedgley Park, Simister",Bury,Park,Coffee Shop,Pub,Deli / Bodega,Duty-free Shop,Donut Shop,Dive Bar,Discount Store
17,M26,53.561610,-2.333690,MANCHESTER,"Radcliffe, Stoneclough","Bury, Bolton",Pub,Pool,Fast Food Restaurant,Furniture / Home Store,Yoga Studio,Dance Studio,Donut Shop,Dive Bar
18,M27,53.512160,-2.336310,MANCHESTER,"Swinton, Clifton, Pendlebury, Wardley, Agecroft",Salford,Supermarket,Pizza Place,Park,Yoga Studio,Deli / Bodega,Duty-free Shop,Donut Shop,Dive Bar
19,M28,53.514670,-2.396660,MANCHESTER,"Worsley, Walkden, Boothstown, Mosley Common, W...","Salford, Wigan",Sports Club,Park,Yoga Studio,Coffee Shop,Duty-free Shop,Donut Shop,Dive Bar,Discount Store
20,M29,53.508160,-2.456920,MANCHESTER,"Tyldesley, Astley",Wigan,Grocery Store,Yoga Studio,Deli / Bodega,Electronics Store,Duty-free Shop,Donut Shop,Dive Bar,Discount Store
21,M30,53.484240,-2.354180,MANCHESTER,"Eccles, Monton, Peel Green, Winton, Patricroft...",Salford,Gym,Grocery Store,Train Station,Pizza Place,Fast Food Restaurant,Sandwich Place,Auto Garage,Yoga Studio
22,M31,53.419300,-2.421360,MANCHESTER,"Carrington, Partington",Trafford,Grocery Store,Antique Shop,Convenience Store,Yoga Studio,Deli / Bodega,Electronics Store,Duty-free Shop,Donut Shop
23,M32,53.450210,-2.308720,MANCHESTER,"Stretford, Trafford Park",Trafford,Gym / Fitness Center,Warehouse Store,Park,Deli / Bodega,Duty-free Shop,Donut Shop,Dive Bar,Discount Store
24,M33,53.420500,-2.325060,SALE,"Sale, Brooklands (Manchester and Trafford)","Trafford, Manchester",Pub,Grocery Store,Supermarket,Chinese Restaurant,Pizza Place,Bookstore,Auto Garage,Tram Station
25,M34,53.455940,-2.117480,MANCHESTER,"Denton, Audenshaw",Tameside,Clothing Store,Mobile Phone Shop,Supermarket,Pharmacy,Café,Coffee Shop,Outlet Store,Shopping Plaza
26,M35,53.507140,-2.152300,MANCHESTER,Failsworth,Oldham,Gym / Fitness Center,Bakery,Construction & Landscaping,Supermarket,Pub,Gay Bar,Gastropub,College Cafeteria
27,M38,53.531670,-2.420960,MANCHESTER,Little Hulton,Salford,Asian Restaurant,Convenience Store,Department Store,Deli / Bodega,Electronics Store,Duty-free Shop,Donut Shop,Dive Bar
28,M4,53.484550,-2.229090,MANCHESTER,"Ancoats, Northern Quarter, Strangeways",Manchester,Bar,Coffee Shop,Pub,Cocktail Bar,Tea Room,Bookstore,Record Shop,Beer Bar
29,M40,53.503490,-2.189990,MANCHESTER,"Collyhurst, Miles Platting, Moston, New Moston...",Manchester,Café,Tram Station,Bus Stop,Pub,Concert Hall,Construction & Landscaping,Comic Shop,Convenience Store
30,M41,53.450950,-2.362940,MANCHESTER,"Urmston, Davyhulme, Flixton, Trafford Park",Trafford,Italian Restaurant,Playground,Convenience Store,Dance Studio,Yoga Studio,Deli / Bodega,Duty-free Shop,Donut Shop
31,M43,53.483780,-2.147700,MANCHESTER,Droylsden,Tameside,Pub,Chinese Restaurant,Supermarket,Pharmacy,Soccer Stadium,Dance Studio,Donut Shop,Dive Bar
32,M44,53.440860,-2.426090,MANCHESTER,"Irlam, Cadishead",Salford,Supermarket,Gym,Warehouse Store,Gas Station,Park,Yoga Studio,Deli / Bodega,Donut Shop
33,M45,53.547340,-2.288290,MANCHESTER,Whitefield,Bury,Indian Restaurant,Fast Food Restaurant,Bakery,Yoga Studio,Department Store,Electronics Store,Duty-free Shop,Donut Shop
34,M46,53.526010,-2.490310,MANCHESTER,Atherton,Wigan,Supermarket,Sandwich Place,Pub,Department Store,Bar,Roller Rink,Soccer Field,Dance Studio
35,M5,53.479030,-2.284820,SALFORD,"Ordsall, Seedley, Weaste, University",Salford,Brewery,Food Truck,Indian Restaurant,Building,Pizza Place,Duty-free Shop,Donut Shop,Dive Bar
36,M6,53.491590,-2.296960,SALFORD,"Pendleton, Irlams o' th' Height, Langworthy, S...",Salford,Supermarket,Yoga Studio,Ethiopian Restaurant,Electronics Store,Duty-free Shop,Donut Shop,Dive Bar,Discount Store
37,M7,53.505160,-2.260860,SALFORD,"Higher Broughton, Cheetwood, Lower Broughton, ...",Salford,Bus Stop,Supermarket,River,Bakery,Deli / Bodega,Duty-free Shop,Donut Shop,Dive Bar
38,M8,53.508800,-2.238270,MANCHESTER,"Crumpsall, Cheetham Hill",Manchester,Grocery Store,Burger Joint,Middle Eastern Restaurant,Tram Station,Restaurant,Asian Restaurant,Park,Light Rail Station
39,M9,53.521430,-2.212690,MANCHESTER,"Harpurhey, Blackley",Manchester,Hotel,Bar,Park,Fish & Chips Shop,Pub,Gift Shop,Gay Bar,Comedy Club
40,M90,53.363090,-2.276530,MANCHESTER,Manchester Airport,Manchester,Coffee Shop,Hotel,Airport Lounge,Duty-free Shop,Restaurant,Sandwich Place,Bookstore,Hotel Bar
41,M50,53.479393,-2.304275,SALFORD,"Salford Quays, MediaCityUK",Salford,Brewery,Bar,Tram Station,Yoga Studio,Department Store,Electronics Store,Duty-free Shop,Donut Shop
42,M99,53.484512,-2.234866,MANCHESTER,Manchester X; JD Williams (located geographica...,Manchester,Bar,Pub,Coffee Shop,Café,Tea Room,Record Shop,Cocktail Bar,Bookstore

## K-mean Cluster Manchester

In [61]:

from sklearn.cluster import KMeans

# set number of clusters
mclusters = 3

m_grouped_clustering = m_grouped.drop('Area', 1)

# run k-means clustering
kmeans = KMeans(n_clusters=mclusters, random_state=0).fit(m_grouped_clustering)

# check cluster labels generated for each row in the dataframe
kmeans.labels_[0:10] 
kmeans.labels_
len(kmeans.labels_)
#create a new dataframe that includes the cluster as well as the top 10 venues for each neighborhood.
# m_merged = bbintang

# add clustering labels
m_merged['Cluster Labels'] = pd.Series(kmeans.labels_)

# merge toronto_grouped with toronto_data to add latitude/longitude for each neighborhood
# bintang_merged = bintang_merged.join(areas_venues_sorted.set_index('Area'), on='Area')

# bintang_merged.head()

In [65]:
# Matplotlib and associated plotting modules
import matplotlib.cm as cm
import matplotlib.colors as colors

#Finally, let's visualize the resulting clusters
# create map 
m_clusters = folium.Map(location=[53.47734, -2.23508], zoom_start=13)

mclusters = 3

# set color scheme for the clusters
x = np.arange(mclusters)
ys = [i+x+(i*x)**2 for i in range(mclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

m_merged= m_merged.fillna(0)

m_merged['Cluster Labels']=m_merged['Cluster Labels'].astype(int)

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(m_merged['latitude'], m_merged['longitude'], m_merged['Area'], m_merged['Cluster Labels']):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(m_clusters)
       
m_clusters

# Analyze Liverpool

In [66]:

# one hot encoding
l_onehot = pd.get_dummies(l_venues[['Venue Category']], prefix="", prefix_sep="")

# add neighborhood column back to dataframe
l_onehot['Area'] = l_venues['Area'] 

# move neighborhood column to the first column
fixed_columns = [l_onehot.columns[-1]] + list(l_onehot.columns[:-1])
l_onehot = l_onehot[fixed_columns]

#examine the new dataframe size after one hot encoding
print('{} rows were returned after one hot encoding.'.format(l_onehot.shape[0]))

#group rows by neighborhood and by taking the mean of the frequency of occurrence of each category
l_grouped = l_onehot.groupby('Area').mean().reset_index()

#examine the new dataframe size after one hot encoding
print('{} rows were returned after grouping.'.format(l_grouped.shape[0]))

698 rows were returned after one hot encoding.
46 rows were returned after grouping.

In [67]:
#print each neighborhood along with the top 5 most common venues
num_top_venues = 5

for hood in l_grouped['Area']:
    print("----"+hood+"----")
    temp = l_grouped[l_grouped['Area'] == hood].T.reset_index()
    temp.columns = ['venue','freq']
    temp = temp.iloc[1:]
    temp['freq'] = temp['freq'].astype(float)
    temp = temp.round({'freq': 2})
    print(temp.sort_values('freq', ascending=False).reset_index(drop=True).head(num_top_venues))
    print('\n')

----Aigburth, St Michael's Hamlet, Sefton Park----
               venue  freq
0                Pub  0.25
1   Botanical Garden  0.25
2  Outdoor Sculpture  0.25
3               Park  0.25
4             Museum  0.00


----Aintree Village, Fazakerley----
                     venue  freq
0             Home Service   1.0
1      American Restaurant   0.0
2    Performing Arts Venue   0.0
3                Nightclub   0.0
4  North Indian Restaurant   0.0


----Aintree, Fazakerley, Orrell Park, Walton----
              venue  freq
0              Café   0.2
1     Grocery Store   0.2
2              Park   0.2
3          Pharmacy   0.2
4  Business Service   0.2


----Allerton, Mossley Hill----
                venue  freq
0  Chinese Restaurant  0.14
1     Thai Restaurant  0.14
2          Restaurant  0.14
3         Coffee Shop  0.14
4         Supermarket  0.14


----American Express[4]----
                 venue  freq
0                  Pub  0.20
1       Discount Store  0.13
2  Sporting Goods Shop  0.13
3      Warehouse Store  0.07
4       Soccer Stadium  0.07


----Anfield, City Centre, Everton, Fairfield, Kensington, Tuebrook----
         venue  freq
0      Brewery  0.33
1          Bar  0.33
2        Hotel  0.33
3  Music Venue  0.00
4    Nightclub  0.00


----Anfield, Everton, Kirkdale, Vauxhall----
                  venue  freq
0           Supermarket   0.2
1        Discount Store   0.2
2  Fast Food Restaurant   0.2
3  Gym / Fitness Center   0.2
4        Shopping Plaza   0.2


----Anfield, Kirkdale, Walton----
                 venue  freq
0  Sporting Goods Shop  0.33
1                  Pub  0.17
2       Soccer Stadium  0.17
3    Outdoor Sculpture  0.17
4                 Park  0.17


----BT Group, large Selectapost users[4]----
                  venue  freq
0                   Bar  0.06
1                 Hotel  0.06
2           Coffee Shop  0.05
3                   Pub  0.05
4  Fast Food Restaurant  0.05


----Belle Vale, Gateacre, Hunts Cross, Woolton, Halewood----
                  venue  freq
0                   Pub   0.2
1         Movie Theater   0.2
2                  Café   0.2
3  Fast Food Restaurant   0.2
4         Garden Center   0.2


----Blundellsands, Brighton-le-Sands, Crosby, Little Crosby, Thornton----
                venue  freq
0                 Bar  0.18
1         Coffee Shop  0.18
2  Italian Restaurant  0.09
3      Discount Store  0.09
4          Restaurant  0.09


----Bootle, Netherton----
                    venue  freq
0          Discount Store   0.3
1  Furniture / Home Store   0.1
2                   Hotel   0.1
3               Multiplex   0.1
4             Supermarket   0.1


----Bootle, Orrell----
                    venue  freq
0          Discount Store  0.12
1                Pharmacy  0.12
2                     Pub  0.06
3  Thrift / Vintage Store  0.06
4           Grocery Store  0.06


----Broadgreen, Bowring Park, Childwall----
                 venue  freq
0        Grocery Store   0.5
1                 Park   0.5
2  American Restaurant   0.0
3               Museum   0.0
4            Nightclub   0.0


----Broadgreen, Dovecot, Knotty Ash, Page Moss----
                  venue  freq
0  Fast Food Restaurant  0.50
1   American Restaurant  0.25
2           Sports Club  0.25
3             Pool Hall  0.00
4             Nightclub  0.00


----Burscough, Mawdesley, Scarisbrick, Rufford, Holmeswood----
                 venue  freq
0                 Café  0.22
1         Soccer Field  0.22
2  American Restaurant  0.11
3        Train Station  0.11
4    Convenience Store  0.11


----City Centre----
         venue  freq
0  Coffee Shop  0.07
1        Hotel  0.07
2          Pub  0.07
3         Café  0.05
4          Bar  0.05


----City Centre, Dingle, Toxteth----
                   venue  freq
0                    Pub  0.25
1               Bus Stop  0.25
2   Gym / Fitness Center  0.25
3          Historic Site  0.25
4  Performing Arts Venue  0.00


----City Centre, Edge Hill, Fairfield, Kensington----
            venue  freq
0  Discount Store   0.2
1   Grocery Store   0.2
2  Clothing Store   0.2
3   Train Station   0.2
4            Park   0.2


----City Centre, Everton, Vauxhall----
           venue  freq
0            Pub  0.14
1          Hotel  0.11
2           Café  0.06
3    Coffee Shop  0.05
4  Grocery Store  0.04


----Clubmoor, Croxteth, Gillmoss, Norris Green----
                     venue  freq
0                     Pool   1.0
1      American Restaurant   0.0
2    Performing Arts Venue   0.0
3                Nightclub   0.0
4  North Indian Restaurant   0.0


----Clubmoor, Old Swan, Stoneycroft, Tuebrook----
                    venue  freq
0       Indian Restaurant  0.25
1                Tea Room  0.25
2             Supermarket  0.25
3  Furniture / Home Store  0.25
4                Platform  0.00


----Croxteth Park, West Derby----
                  venue  freq
0          Soccer Field  0.50
1           Supermarket  0.25
2  Fast Food Restaurant  0.25
3   American Restaurant  0.00
4                  Park  0.00


----Ford, Litherland, Seaforth----
                  venue  freq
0              Gym Pool   0.2
1  Fast Food Restaurant   0.2
2        Sandwich Place   0.2
3        Clothing Store   0.2
4                  Café   0.2


----Formby, Little Altcar, Great Altcar----
                    venue  freq
0             Coffee Shop   0.2
1           Grocery Store   0.2
2  Thrift / Vintage Store   0.1
3      Italian Restaurant   0.1
4       Convenience Store   0.1


----Garston, Grassendale, Aigburth,----
         venue  freq
0          Pub  0.33
1         Pool  0.17
2   Playground  0.17
3  Supermarket  0.17
4         Café  0.17


----HM Revenue and Customs (Customs and Excise)[4]----
                  venue  freq
0                 Hotel  0.20
1       Harbor / Marina  0.20
2     Indian Restaurant  0.07
3            Restaurant  0.07
4  Fast Food Restaurant  0.07


----HM Revenue and Customs (Inland Revenue)[4]----
                        venue  freq
0  Construction & Landscaping  0.33
1               Train Station  0.33
2                     Brewery  0.17
3                 IT Services  0.17
4            Video Game Store  0.00


----Hale, Speke----
                 venue  freq
0          Supermarket  0.25
1    Food & Drink Shop  0.25
2       Clothing Store  0.25
3                 Café  0.25
4  American Restaurant  0.00


----Halewood----
            venue  freq
0  Shopping Plaza   0.2
1     Supermarket   0.2
2  Discount Store   0.2
3  Sandwich Place   0.2
4   Grocery Store   0.2


----Huyton, Roby, Tarbock----
                  venue  freq
0  Fast Food Restaurant  0.22
1           Coffee Shop  0.22
2                   Pub  0.11
3     Mobile Phone Shop  0.11
4           Supermarket  0.11


----Ince Blundell, Hightown----
                venue  freq
0                 Pub  0.25
1       Train Station  0.25
2                Park  0.25
3      Breakfast Spot  0.25
4  Italian Restaurant  0.00


----Kirkby----
                  venue  freq
0                Market   0.2
1  Gym / Fitness Center   0.2
2        Discount Store   0.2
3        Sandwich Place   0.2
4         Shopping Mall   0.2


----Kirkdale----
                    venue  freq
0          Discount Store  0.12
1                Pharmacy  0.12
2                     Pub  0.06
3  Thrift / Vintage Store  0.06
4           Grocery Store  0.06


----Littlewoods Pools[4]----
                venue  freq
0                 Pub  0.19
1             Stadium  0.12
2              Bakery  0.12
3      Soccer Stadium  0.12
4  Chinese Restaurant  0.06


----Littlewoods[4]----
                     venue  freq
0      American Restaurant   0.5
1                     Park   0.5
2    Performing Arts Venue   0.0
3                Nightclub   0.0
4  North Indian Restaurant   0.0


----Maghull, Lydiate, Melling, Waddicar----
                 venue  freq
0                  Pub  0.25
1     Greek Restaurant  0.25
2          Supermarket  0.25
3       Breakfast Spot  0.25
4  Japanese Restaurant  0.00


----Netherley----
                        venue  freq
0  Construction & Landscaping   0.2
1       Performing Arts Venue   0.2
2        Ethiopian Restaurant   0.2
3                 Pizza Place   0.2
4               Indie Theater   0.2


----Ormskirk, Aughton----
                     venue  freq
0      Arts & Crafts Store   0.5
1                  Dog Run   0.5
2      American Restaurant   0.0
3                 Pharmacy   0.0
4  North Indian Restaurant   0.0


----PO boxes in central Liverpool, government departments in Liverpool and Bootle, University of Liverpool[4]----
               venue  freq
0      Grocery Store  0.09
1              Hotel  0.07
2                Pub  0.04
3        Coffee Shop  0.04
4  Convenience Store  0.04


----Prescot, Knowsley Village----
         venue  freq
0  Zoo Exhibit  0.50
1   Playground  0.17
2  Bridal Shop  0.17
3          Zoo  0.17
4         Pool  0.00


----Stockbridge Village----
                        venue  freq
0  Construction & Landscaping  0.33
1               Movie Theater  0.33
2           Convenience Store  0.33
3          Italian Restaurant  0.00
4     North Indian Restaurant  0.00


----Vernons Pools[4]----
                        venue  freq
0  Construction & Landscaping  0.17
1              Soccer Stadium  0.17
2                Soccer Field  0.17
3               Train Station  0.17
4        Gym / Fitness Center  0.17


----Waterloo----
                venue  freq
0                 Pub  0.25
1       Grocery Store  0.25
2  Spanish Restaurant  0.08
3       Movie Theater  0.08
4          Restaurant  0.08


----Wavertree----
               venue  freq
0      Grocery Store  0.25
1               Pool  0.12
2  Indian Restaurant  0.12
3                Gym  0.12
4              Track  0.12


----seasonal response mail[4]----
               venue  freq
0        Coffee Shop  0.15
1     Sandwich Place  0.12
2  Convenience Store  0.12
3              Hotel  0.08
4      Grocery Store  0.08

In [68]:
#put into a pandas dataframe

#write a function to sort the venues in descending order
def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    
    return row_categories_sorted.index.values[0:num_top_venues]

#create the new dataframe and display the top 10 venues for each neighborhood
num_top_venues = 8

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['Area']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
areas_venues_sorted = pd.DataFrame(columns=columns)
areas_venues_sorted['Area'] = l_grouped['Area']

for ind in np.arange(l_grouped.shape[0]):
    areas_venues_sorted.iloc[ind, 1:] = return_most_common_venues(l_grouped.iloc[ind, :], num_top_venues)

areas_venues_sorted.head()

,Area,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue
0,"Aigburth, St Michael's Hamlet, Sefton Park",Park,Outdoor Sculpture,Botanical Garden,Pub,Fast Food Restaurant,Falafel Restaurant,Ethiopian Restaurant,English Restaurant
1,"Aintree Village, Fazakerley",Home Service,Zoo Exhibit,Donut Shop,Food & Drink Shop,Fast Food Restaurant,Falafel Restaurant,Ethiopian Restaurant,English Restaurant
2,"Aintree, Fazakerley, Orrell Park, Walton",Café,Grocery Store,Pharmacy,Park,Business Service,Falafel Restaurant,Ethiopian Restaurant,English Restaurant
3,"Allerton, Mossley Hill",Coffee Shop,Chinese Restaurant,Restaurant,Supermarket,Grocery Store,Thai Restaurant,Sandwich Place,Discount Store
4,American Express[4],Pub,Sporting Goods Shop,Discount Store,Outdoor Sculpture,Soccer Stadium,Supermarket,Sandwich Place,Bus Stop

In [70]:
l_merged = df_l
l_merged.rename(columns={'Coverage':'Area'}, inplace=True)

l_grouped_clustering = l_grouped.drop('Area', 1)
l_grouped_clustering

l_merged=l_merged.join(areas_venues_sorted.set_index('Area'),on='Area')
l_merged.head()

,postcode,latitude,longitude,Post town,Area,Local authority area,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue
0,L1,53.40254,-2.97928,LIVERPOOL,City Centre,Liverpool,Hotel,Pub,Coffee Shop,Bar,Café,Italian Restaurant,Clothing Store,Burger Joint
1,L10,53.47398,-2.92668,LIVERPOOL,"Aintree Village, Fazakerley","Sefton, Liverpool, Knowsley",Home Service,Zoo Exhibit,Donut Shop,Food & Drink Shop,Fast Food Restaurant,Falafel Restaurant,Ethiopian Restaurant,English Restaurant
2,L11,53.44801,-2.91407,LIVERPOOL,"Clubmoor, Croxteth, Gillmoss, Norris Green",Liverpool,Pool,Hotel,Food & Drink Shop,Fast Food Restaurant,Falafel Restaurant,Ethiopian Restaurant,English Restaurant,Electronics Store
3,L12,53.43467,-2.89421,LIVERPOOL,"Croxteth Park, West Derby",Liverpool,Soccer Field,Fast Food Restaurant,Supermarket,Zoo Exhibit,Donut Shop,Falafel Restaurant,Ethiopian Restaurant,English Restaurant
4,L13,53.41740,-2.91943,LIVERPOOL,"Clubmoor, Old Swan, Stoneycroft, Tuebrook",Liverpool,Furniture / Home Store,Indian Restaurant,Supermarket,Tea Room,Electronics Store,Food & Drink Shop,Fast Food Restaurant,Falafel Restaurant

## K-mean Cluster Liverpool

In [72]:


from sklearn.cluster import KMeans

# set number of clusters
lclusters = 3

l_grouped_clustering = l_grouped.drop('Area', 1)

# run k-means clustering
kmeans = KMeans(n_clusters=lclusters, random_state=0).fit(l_grouped_clustering)

# check cluster labels generated for each row in the dataframe
kmeans.labels_[0:10] 
kmeans.labels_
len(kmeans.labels_)
#create a new dataframe that includes the cluster as well as the top 10 venues for each neighborhood.


# add clustering labels
l_merged['Cluster Labels'] = pd.Series(kmeans.labels_)



# Matplotlib and associated plotting modules
import matplotlib.cm as cm
import matplotlib.colors as colors

#Finally, let's visualize the resulting clusters
# create map 
l_clusters = folium.Map(location=[53.40254, -2.97928], zoom_start=13)

lclusters = 3

# set color scheme for the clusters
x = np.arange(lclusters)
ys = [i+x+(i*x)**2 for i in range(lclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

l_merged= l_merged.fillna(0)

l_merged['Cluster Labels']=l_merged['Cluster Labels'].astype(int)

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(l_merged['latitude'], l_merged['longitude'], l_merged['Area'], l_merged['Cluster Labels']):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(l_clusters)
       
l_clusters

# Results

### Let's see the top three clusters of Manchester

In [73]:
m_merged.loc[m_merged['Cluster Labels'] == 0, m_merged.columns[[2] + list(range(5, m_merged.shape[1]))]]

,longitude,Local authority area,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,Cluster Labels
0,-2.235080,Manchester,Hotel,Gay Bar,Bar,Pub,Coffee Shop,Cocktail Bar,Sushi Restaurant,Indian Restaurant,0
3,-2.213890,Manchester,College Cafeteria,Asian Restaurant,Park,Liquor Store,Bus Stop,Pharmacy,Convenience Store,Cosmetics Shop,0
15,-2.196240,"Rochdale, Oldham",Stadium,Pub,Grocery Store,Supermarket,Deli / Bodega,Duty-free Shop,Donut Shop,Dive Bar,0
19,-2.396660,"Salford, Wigan",Sports Club,Park,Yoga Studio,Coffee Shop,Duty-free Shop,Donut Shop,Dive Bar,Discount Store,0
21,-2.354180,Salford,Gym,Grocery Store,Train Station,Pizza Place,Fast Food Restaurant,Sandwich Place,Auto Garage,Yoga Studio,0
28,-2.229090,Manchester,Bar,Coffee Shop,Pub,Cocktail Bar,Tea Room,Bookstore,Record Shop,Beer Bar,0
35,-2.284820,Salford,Brewery,Food Truck,Indian Restaurant,Building,Pizza Place,Duty-free Shop,Donut Shop,Dive Bar,0
36,-2.296960,Salford,Supermarket,Yoga Studio,Ethiopian Restaurant,Electronics Store,Duty-free Shop,Donut Shop,Dive Bar,Discount Store,0
42,-2.234866,Manchester,Bar,Pub,Coffee Shop,Café,Tea Room,Record Shop,Cocktail Bar,Bookstore,0

In [74]:
m_merged.loc[m_merged['Cluster Labels'] == 1, m_merged.columns[[2] + list(range(5, m_merged.shape[1]))]]

,longitude,Local authority area,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,Cluster Labels
1,-2.179330,Manchester,Indian Restaurant,Yoga Studio,Deli / Bodega,Electronics Store,Duty-free Shop,Donut Shop,Dive Bar,Discount Store,1
2,-2.201870,Manchester,College Cafeteria,Asian Restaurant,Park,Liquor Store,Bus Stop,Pharmacy,Convenience Store,Cosmetics Shop,1
4,-2.224370,Manchester,Gym / Fitness Center,Bed & Breakfast,Fried Chicken Joint,Park,Racetrack,Bus Station,Coffee Shop,Art Gallery,1
5,-2.250080,"Manchester, Trafford",Café,Grocery Store,Deli / Bodega,Discount Store,Vegetarian / Vegan Restaurant,Park,Convenience Store,Fast Food Restaurant,1
6,-2.263570,"Manchester, Trafford",Grocery Store,Bus Stop,Sandwich Place,Yoga Studio,Duty-free Shop,Donut Shop,Dive Bar,Discount Store,1
8,-2.168710,Manchester,Gym / Fitness Center,Hotel,Gym,Supermarket,Sandwich Place,Market,Deli / Bodega,Donut Shop,1
9,-2.194210,"Manchester, Stockport",Gym / Fitness Center,Restaurant,Indoor Play Area,Pakistani Restaurant,Park,Deli / Bodega,Donut Shop,Dive Bar,1
10,-2.242630,Manchester,Coffee Shop,Italian Restaurant,Steakhouse,Hotel,Asian Restaurant,Pub,Plaza,Thai Restaurant,1
11,-2.230270,Manchester,Pizza Place,Bus Station,Wine Bar,Gym / Fitness Center,Tram Station,Thai Restaurant,Tennis Court,Deli / Bodega,1
12,-2.270990,Manchester,Grocery Store,Bar,Indian Restaurant,Gas Station,Japanese Restaurant,Falafel Restaurant,Fabric Shop,Music Venue,1
13,-2.258630,Manchester,Tram Station,Coffee Shop,Supermarket,Dance Studio,Duty-free Shop,Donut Shop,Dive Bar,Discount Store,1
14,-2.287290,"Manchester, Trafford",Park,Fast Food Restaurant,Tram Station,Yoga Studio,Deli / Bodega,Duty-free Shop,Donut Shop,Dive Bar,1
16,-2.274590,Bury,Park,Coffee Shop,Pub,Deli / Bodega,Duty-free Shop,Donut Shop,Dive Bar,Discount Store,1
17,-2.333690,"Bury, Bolton",Pub,Pool,Fast Food Restaurant,Furniture / Home Store,Yoga Studio,Dance Studio,Donut Shop,Dive Bar,1
18,-2.336310,Salford,Supermarket,Pizza Place,Park,Yoga Studio,Deli / Bodega,Duty-free Shop,Donut Shop,Dive Bar,1
20,-2.456920,Wigan,Grocery Store,Yoga Studio,Deli / Bodega,Electronics Store,Duty-free Shop,Donut Shop,Dive Bar,Discount Store,1
22,-2.421360,Trafford,Grocery Store,Antique Shop,Convenience Store,Yoga Studio,Deli / Bodega,Electronics Store,Duty-free Shop,Donut Shop,1
23,-2.308720,Trafford,Gym / Fitness Center,Warehouse Store,Park,Deli / Bodega,Duty-free Shop,Donut Shop,Dive Bar,Discount Store,1
24,-2.325060,"Trafford, Manchester",Pub,Grocery Store,Supermarket,Chinese Restaurant,Pizza Place,Bookstore,Auto Garage,Tram Station,1
25,-2.117480,Tameside,Clothing Store,Mobile Phone Shop,Supermarket,Pharmacy,Café,Coffee Shop,Outlet Store,Shopping Plaza,1
26,-2.152300,Oldham,Gym / Fitness Center,Bakery,Construction & Landscaping,Supermarket,Pub,Gay Bar,Gastropub,College Cafeteria,1
27,-2.420960,Salford,Asian Restaurant,Convenience Store,Department Store,Deli / Bodega,Electronics Store,Duty-free Shop,Donut Shop,Dive Bar,1
29,-2.189990,Manchester,Café,Tram Station,Bus Stop,Pub,Concert Hall,Construction & Landscaping,Comic Shop,Convenience Store,1
30,-2.362940,Trafford,Italian Restaurant,Playground,Convenience Store,Dance Studio,Yoga Studio,Deli / Bodega,Duty-free Shop,Donut Shop,1
31,-2.147700,Tameside,Pub,Chinese Restaurant,Supermarket,Pharmacy,Soccer Stadium,Dance Studio,Donut Shop,Dive Bar,1
32,-2.426090,Salford,Supermarket,Gym,Warehouse Store,Gas Station,Park,Yoga Studio,Deli / Bodega,Donut Shop,1
33,-2.288290,Bury,Indian Restaurant,Fast Food Restaurant,Bakery,Yoga Studio,Department Store,Electronics Store,Duty-free Shop,Donut Shop,1
34,-2.490310,Wigan,Supermarket,Sandwich Place,Pub,Department Store,Bar,Roller Rink,Soccer Field,Dance Studio,1
37,-2.260860,Salford,Bus Stop,Supermarket,River,Bakery,Deli / Bodega,Duty-free Shop,Donut Shop,Dive Bar,1
38,-2.238270,Manchester,Grocery Store,Burger Joint,Middle Eastern Restaurant,Tram Station,Restaurant,Asian Restaurant,Park,Light Rail Station,1
40,-2.276530,Manchester,Coffee Shop,Hotel,Airport Lounge,Duty-free Shop,Restaurant,Sandwich Place,Bookstore,Hotel Bar,1
41,-2.304275,Salford,Brewery,Bar,Tram Station,Yoga Studio,Department Store,Electronics Store,Duty-free Shop,Donut Shop,1

In [75]:
m_merged.loc[m_merged['Cluster Labels'] == 2, m_merged.columns[[2] + list(range(5, m_merged.shape[1]))]]

,longitude,Local authority area,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,Cluster Labels
7,-2.31789,Trafford,Sandwich Place,Yoga Studio,Deli / Bodega,Electronics Store,Duty-free Shop,Donut Shop,Dive Bar,Discount Store,2
39,-2.21269,Manchester,Hotel,Bar,Park,Fish & Chips Shop,Pub,Gift Shop,Gay Bar,Comedy Club,2

### The top three clusters of Liverpool

In [76]:
l_merged.loc[l_merged['Cluster Labels'] == 0, l_merged.columns[[2] + list(range(5, l_merged.shape[1]))]]

,longitude,Local authority area,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,Cluster Labels
20,-2.837580,Liverpool,Construction & Landscaping,Pizza Place,Indie Theater,Ethiopian Restaurant,Performing Arts Venue,Donut Shop,Food & Drink Shop,Fast Food Restaurant,0
46,-2.988368,non-geographic,American Restaurant,Park,Hotel,Food & Drink Shop,Fast Food Restaurant,Falafel Restaurant,Ethiopian Restaurant,English Restaurant,0
47,-2.975554,non-geographic,Bar,Hotel,Pub,Coffee Shop,Fast Food Restaurant,Theater,Comic Shop,Middle Eastern Restaurant,0
48,-2.988061,non-geographic,Hotel,Harbor / Marina,Hostel,Pub,Music Venue,Seafood Restaurant,Bed & Breakfast,Rental Car Location,0
49,-2.985222,non-geographic,Construction & Landscaping,Train Station,Brewery,IT Services,Convenience Store,Cosmetics Shop,Department Store,Dessert Shop,0

In [77]:
l_merged.loc[l_merged['Cluster Labels'] == 1, l_merged.columns[[2] + list(range(5, l_merged.shape[1]))]]

,longitude,Local authority area,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,Cluster Labels
0,-2.979280,Liverpool,Hotel,Pub,Coffee Shop,Bar,Café,Italian Restaurant,Clothing Store,Burger Joint,1
1,-2.926680,"Sefton, Liverpool, Knowsley",Home Service,Zoo Exhibit,Donut Shop,Food & Drink Shop,Fast Food Restaurant,Falafel Restaurant,Ethiopian Restaurant,English Restaurant,1
4,-2.919430,Liverpool,Furniture / Home Store,Indian Restaurant,Supermarket,Tea Room,Electronics Store,Food & Drink Shop,Fast Food Restaurant,Falafel Restaurant,1
5,-2.878830,"Liverpool, Knowsley",Fast Food Restaurant,American Restaurant,Sports Club,Cosmetics Shop,Department Store,Dessert Shop,Diner,Discount Store,1
6,-2.919010,Liverpool,Grocery Store,Pool,Track,Park,Bar,Gym,Indian Restaurant,Department Store,1
7,-2.887440,"Liverpool, Knowsley",Grocery Store,Park,Zoo Exhibit,French Restaurant,Fast Food Restaurant,Falafel Restaurant,Ethiopian Restaurant,English Restaurant,1
8,-2.939620,Liverpool,Park,Outdoor Sculpture,Botanical Garden,Pub,Fast Food Restaurant,Falafel Restaurant,Ethiopian Restaurant,English Restaurant,1
9,-2.906610,Liverpool,Coffee Shop,Chinese Restaurant,Restaurant,Supermarket,Grocery Store,Thai Restaurant,Sandwich Place,Discount Store,1
11,-2.988410,Liverpool,Hotel,Pub,Coffee Shop,Bar,Café,Italian Restaurant,Clothing Store,Burger Joint,1
12,-2.987970,"Sefton, Liverpool",Pharmacy,Discount Store,Stationery Store,Supermarket,Pub,Grocery Store,Thrift / Vintage Store,Coffee Shop,1
14,-2.998930,"Sefton, Liverpool",Sandwich Place,Fast Food Restaurant,Clothing Store,Gym Pool,Café,Dog Run,Falafel Restaurant,Ethiopian Restaurant,1
15,-3.026200,Sefton,Grocery Store,Pub,Gym / Fitness Center,Sandwich Place,Spanish Restaurant,Restaurant,Movie Theater,Asian Restaurant,1
16,-3.022030,Sefton,Coffee Shop,Bar,Italian Restaurant,Discount Store,Tapas Restaurant,Gym,Grocery Store,Restaurant,1
17,-2.836720,"Halton, Liverpool",Food & Drink Shop,Clothing Store,Supermarket,Café,Zoo Exhibit,Electronics Store,Fast Food Restaurant,Falafel Restaurant,1
19,-2.832620,"Liverpool, Knowsley",Grocery Store,Supermarket,Shopping Plaza,Discount Store,Sandwich Place,Dog Run,Falafel Restaurant,Ethiopian Restaurant,1
22,-2.983190,Sefton,0,0,0,0,0,0,0,0,1
23,-2.983940,Liverpool,Pub,Hotel,Café,Coffee Shop,Grocery Store,Bar,Clothing Store,Restaurant,1
25,-2.936590,Sefton,Greek Restaurant,Pub,Supermarket,Breakfast Spot,Zoo Exhibit,Fast Food Restaurant,Falafel Restaurant,Ethiopian Restaurant,1
26,-2.889090,Knowsley,Sandwich Place,Market,Discount Store,Gym / Fitness Center,Shopping Mall,Donut Shop,Falafel Restaurant,Ethiopian Restaurant,1
27,-2.875770,Knowsley,Sandwich Place,Market,Discount Store,Gym / Fitness Center,Shopping Mall,Donut Shop,Falafel Restaurant,Ethiopian Restaurant,1
30,-2.839620,Knowsley,Coffee Shop,Fast Food Restaurant,Bus Station,Pub,Mobile Phone Shop,Furniture / Home Store,Supermarket,Convenience Store,1
31,-3.062880,"Sefton, West Lancashire",Coffee Shop,Grocery Store,Convenience Store,English Restaurant,Restaurant,Italian Restaurant,Thrift / Vintage Store,Supermarket,1
32,-3.049980,"Sefton, West Lancashire",Pub,Train Station,Breakfast Spot,Park,Zoo Exhibit,Donut Shop,Fast Food Restaurant,Falafel Restaurant,1
33,-2.895370,West Lancashire,Dog Run,Arts & Crafts Store,Donut Shop,Food & Drink Shop,Fast Food Restaurant,Falafel Restaurant,Ethiopian Restaurant,English Restaurant,1
34,-2.960520,Liverpool,Sporting Goods Shop,Pub,Soccer Stadium,Park,Outdoor Sculpture,Department Store,Dessert Shop,Diner,1
35,-2.840320,"West Lancashire, Chorley",Café,Soccer Field,Pub,Restaurant,Train Station,American Restaurant,Convenience Store,Cosmetics Shop,1
36,-2.975290,Liverpool,Discount Store,Gym / Fitness Center,Supermarket,Shopping Plaza,Fast Food Restaurant,Department Store,Dessert Shop,Diner,1
37,-2.949560,Liverpool,Brewery,Hotel,Bar,Electronics Store,French Restaurant,Food & Drink Shop,Fast Food Restaurant,Falafel Restaurant,1
38,-2.973370,non-geographic,Grocery Store,Hotel,Convenience Store,Coffee Shop,Sandwich Place,Pub,Fast Food Restaurant,Mediterranean Restaurant,1
39,-2.947760,Liverpool,Discount Store,Grocery Store,Clothing Store,Train Station,Park,Falafel Restaurant,Ethiopian Restaurant,English Restaurant,1
40,-2.970400,non-geographic,Coffee Shop,Convenience Store,Sandwich Place,Hotel,Grocery Store,Bakery,Italian Restaurant,Music Venue,1
41,-2.962460,Liverpool,Gym / Fitness Center,Pub,Historic Site,Bus Stop,Dog Run,Falafel Restaurant,Ethiopian Restaurant,English Restaurant,1
42,-2.952010,"Liverpool, Sefton",Café,Grocery Store,Pharmacy,Park,Business Service,Falafel Restaurant,Ethiopian Restaurant,English Restaurant,1
43,-2.958583,non-geographic,Pub,Soccer Stadium,Stadium,Bakery,Buffet,Museum,Souvenir Shop,Restaurant,1

In [78]:
l_merged.loc[l_merged['Cluster Labels'] == 2, l_merged.columns[[2] + list(range(5, l_merged.shape[1]))]]

,longitude,Local authority area,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,Cluster Labels
2,-2.914070,Liverpool,Pool,Hotel,Food & Drink Shop,Fast Food Restaurant,Falafel Restaurant,Ethiopian Restaurant,English Restaurant,Electronics Store,2
3,-2.894210,Liverpool,Soccer Field,Fast Food Restaurant,Supermarket,Zoo Exhibit,Donut Shop,Falafel Restaurant,Ethiopian Restaurant,English Restaurant,2
10,-2.901650,Liverpool,Pub,Pool,Supermarket,Café,Playground,Convenience Store,Cosmetics Shop,Department Store,2
13,-2.987970,Liverpool,Pharmacy,Discount Store,Stationery Store,Supermarket,Pub,Grocery Store,Thrift / Vintage Store,Coffee Shop,2
18,-2.862960,"Liverpool, Knowsley",Movie Theater,Garden Center,Fast Food Restaurant,Café,Pub,Cosmetics Shop,Department Store,Dessert Shop,2
21,-2.864110,"Liverpool, Knowsley",Movie Theater,Convenience Store,Construction & Landscaping,Home Service,French Restaurant,Hostel,Cosmetics Shop,Department Store,2
24,-2.970620,Sefton,Discount Store,Hotel,Furniture / Home Store,Supermarket,Soccer Field,Bus Stop,Clothing Store,Multiplex,2
28,-2.814450,Knowsley,Zoo Exhibit,Bridal Shop,Playground,Zoo,Art Museum,Electronics Store,French Restaurant,Food & Drink Shop,2
29,-2.782440,"Knowsley, St Helens",0,0,0,0,0,0,0,0,2
44,-2.960690,non-geographic,Construction & Landscaping,Soccer Stadium,Soccer Field,Train Station,English Restaurant,Gym / Fitness Center,Zoo Exhibit,Donut Shop,2
45,-2.971429,non-geographic,Pub,Sporting Goods Shop,Discount Store,Outdoor Sculpture,Soccer Stadium,Supermarket,Sandwich Place,Bus Stop,2

# Discussion

As mentioned in the Introduction section, both of the two cities are important and popular in the UK. With what we've calculated and mapped in the last section, we can briefly classify the clusters of the two cities using the data of the most common venue.

For Manchester, cluster 1 is more likely for leisure/tourism (bar&pub), cluster 2 is for residential and cluster 3 is for shopping. For Liverpool, cluster 1 is likely for tourism as the cluster 1 of Manchester, cluster 2 is for residential and cluster 3 is mixed of leisure and residential. Based on the clusters calculated, we can draw a conclusion that the two cities are similar in terms of the common venues. 

There are several possible explanations for this result. Both of the two cities have highly-reputed football clubs and and museums, therefore, both of them attract people to visit. There are also high ranked universities located in the two cities, so this preliminary finding also suggests that the two cities are suitable for residential. 

In addition, if you are a university student live around the University and also like Chinese food then Liverpool provides you more choices than Manchester :)

# Conclusion

This project compared two big cities in the North of England, classified the area in the city whether it's for residential, social or others. This was derived using Foursquare data. So the limitation is it was not a all through comparison. We can not jump into a conclusion that which city is better than another. 

In the future, we need to consider use other quantitative data such as living cost, house price and job market etc to have a further exploration.